{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6250c310-7026-4069-9ae2-25ac8e580636",
   "metadata": {
    "tags": []
   },
   "outputs": [],
   "source": [
    "%pip install modin s3fs"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "a1d65d37-6a53-4473-beae-4c7d8a2ea3fa",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2022-07-06T11:55:07.169466Z",
     "iopub.status.busy": "2022-07-06T11:55:07.169141Z",
     "iopub.status.idle": "2022-07-06T11:55:11.624105Z",
     "shell.execute_reply": "2022-07-06T11:55:11.623360Z",
     "shell.execute_reply.started": "2022-07-06T11:55:07.169377Z"
    },
    "tags": []
   },
   "outputs": [
    {
     "data": {
      "text/plain": [
       "ClientContext(dashboard_url='127.0.0.1:8265', python_version='3.7.10', ray_version='1.13.0', ray_commit='e4ce38d001dbbe09cd21c497fedd03d692b2be3e', protocol_version='2022-03-16', _num_clients=8, _context_to_restore=<ray.util.client._ClientContext object at 0x7f79781bc910>)"
      ]
     },
     "execution_count": 1,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import ray\n",
    "\n",
    "ray.shutdown()\n",
    "ray.init(address=\"ray://localhost:10001\",\n",
    "         runtime_env={\"pip\": [\"s3fs\", \"modin\"]})"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "390b8312-fbd8-462f-9534-dd48e5173447",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2022-07-06T11:58:13.811853Z",
     "iopub.status.busy": "2022-07-06T11:58:13.811630Z",
     "iopub.status.idle": "2022-07-06T12:16:23.821894Z",
     "shell.execute_reply": "2022-07-06T12:16:23.820801Z",
     "shell.execute_reply.started": "2022-07-06T11:58:13.811829Z"
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: 42d4605e8adc170a0a807ab3c454f6061185062a17000000 Worker ID: c77e7c6e49f22ed123d626c1b3bb0a95fc8a86dd31cb72a7071e307a Node ID: eca4b6a7a70cf9efb4db903ac9e8c686185a0844592e18ab182034d8 Worker IP address: 172.31.26.33 Worker port: 10045 Worker PID: 3970\n",
      "A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: a0f24f5a9a222c02c1439738a55c740a5357c68c17000000 Worker ID: 8b1138d34e2e8da0d9b77b02dad65052fe81e3a598402c8fbc3d1b10 Node ID: eca4b6a7a70cf9efb4db903ac9e8c686185a0844592e18ab182034d8 Worker IP address: 172.31.26.33 Worker port: 10044 Worker PID: 3969\n",
      "\u001b[2m\u001b[36m(deploy_ray_func pid=6873, ip=172.31.26.33)\u001b[0m terminate called after throwing an instance of 'std::bad_alloc'\n",
      "\u001b[2m\u001b[36m(deploy_ray_func pid=6873, ip=172.31.26.33)\u001b[0m   what():  std::bad_alloc\n",
      "\u001b[2m\u001b[36m(deploy_ray_func pid=6873, ip=172.31.26.33)\u001b[0m *** SIGABRT received at time=1657108853 on cpu 0 ***\n",
      "\u001b[2m\u001b[36m(deploy_ray_func pid=6873, ip=172.31.26.33)\u001b[0m PC: @     0x7fee337f1ca0  (unknown)  raise\n",
      "\u001b[2m\u001b[36m(deploy_ray_func pid=6873, ip=172.31.26.33)\u001b[0m     @     0x7fee342c18e0  (unknown)  (unknown)\n",
      "\u001b[2m\u001b[36m(deploy_ray_func pid=6873, ip=172.31.26.33)\u001b[0m     @     0x7fee33b64760  (unknown)  (unknown)\n",
      "\u001b[2m\u001b[36m(deploy_ray_func pid=6873, ip=172.31.26.33)\u001b[0m     @     0x7fee33b64703  (unknown)  (unknown)\n",
      "\u001b[2m\u001b[36m(deploy_ray_func pid=6873, ip=172.31.26.33)\u001b[0m [2022-07-06 12:00:53,430 E 6873 6978] logging.cc:325: *** SIGABRT received at time=1657108853 on cpu 0 ***\n",
      "\u001b[2m\u001b[36m(deploy_ray_func pid=6873, ip=172.31.26.33)\u001b[0m [2022-07-06 12:00:53,430 E 6873 6978] logging.cc:325: PC: @     0x7fee337f1ca0  (unknown)  raise\n",
      "\u001b[2m\u001b[36m(deploy_ray_func pid=6873, ip=172.31.26.33)\u001b[0m [2022-07-06 12:00:53,432 E 6873 6978] logging.cc:325:     @     0x7fee342c18e0  (unknown)  (unknown)\n",
      "\u001b[2m\u001b[36m(deploy_ray_func pid=6873, ip=172.31.26.33)\u001b[0m [2022-07-06 12:00:53,434 E 6873 6978] logging.cc:325:     @     0x7fee33b64760  (unknown)  (unknown)\n",
      "\u001b[2m\u001b[36m(deploy_ray_func pid=6873, ip=172.31.26.33)\u001b[0m [2022-07-06 12:00:53,437 E 6873 6978] logging.cc:325:     @     0x7fee33b64703  (unknown)  (unknown)\n",
      "\u001b[2m\u001b[36m(deploy_ray_func pid=6873, ip=172.31.26.33)\u001b[0m Fatal Python error: Aborted\n",
      "\u001b[2m\u001b[36m(deploy_ray_func pid=6873, ip=172.31.26.33)\u001b[0m \n",
      "\u001b[2m\u001b[36m(deploy_ray_func pid=6873, ip=172.31.26.33)\u001b[0m Stack (most recent call first):\n",
      "A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: 8a5fe8a8d5753b1563197570faeb2b8c68a12f0217000000 Worker ID: 98f9b5216db2d4324e2fab0ce3c575e35f67bb21423596ac2d53a775 Node ID: eca4b6a7a70cf9efb4db903ac9e8c686185a0844592e18ab182034d8 Worker IP address: 172.31.26.33 Worker port: 10052 Worker PID: 6873\n",
      "A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: bf4232322fce045a773879d46a7e6df179c2543f17000000 Worker ID: 5b7d759943cf8f0b46b3282faca8cfca81db0f8eac20debc2c080bfc Node ID: eca4b6a7a70cf9efb4db903ac9e8c686185a0844592e18ab182034d8 Worker IP address: 172.31.26.33 Worker port: 10046 Worker PID: 3973\n",
      "A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: e129456da0c9dc4df248123882f6b1b70aaa2af317000000 Worker ID: 0f27081572d5a75f7799c5bad051366da1f5ca6dcef06541d613d579 Node ID: eca4b6a7a70cf9efb4db903ac9e8c686185a0844592e18ab182034d8 Worker IP address: 172.31.26.33 Worker port: 10043 Worker PID: 3907\n",
      "The node with node id: 5fe5a04368d8c94ac607757c58e4ed45324d2ae691b76808ee069e4a and address: 172.31.29.141 and node name: 172.31.29.141 has been marked dead because the detector has missed too many heartbeats from it. This can happen when a raylet crashes unexpectedly or has lagging heartbeats.\n",
      "\u001b[2m\u001b[33m(raylet, ip=172.31.29.141)\u001b[0m [2022-07-06 12:16:23,113 C 18274 18274] (raylet) node_manager.cc:170: This node has beem marked as dead.\n",
      "\u001b[2m\u001b[33m(raylet, ip=172.31.29.141)\u001b[0m *** StackTrace Information ***\n",
      "\u001b[2m\u001b[33m(raylet, ip=172.31.29.141)\u001b[0m     ray::SpdLogMessage::Flush()\n",
      "\u001b[2m\u001b[33m(raylet, ip=172.31.29.141)\u001b[0m     ray::RayLog::~RayLog()\n",
      "\u001b[2m\u001b[33m(raylet, ip=172.31.29.141)\u001b[0m     std::_Function_handler<>::_M_invoke()\n",
      "\u001b[2m\u001b[33m(raylet, ip=172.31.29.141)\u001b[0m     std::_Function_handler<>::_M_invoke()\n",
      "\u001b[2m\u001b[33m(raylet, ip=172.31.29.141)\u001b[0m     std::_Function_handler<>::_M_invoke()\n",
      "\u001b[2m\u001b[33m(raylet, ip=172.31.29.141)\u001b[0m     ray::rpc::ClientCallImpl<>::OnReplyReceived()\n",
      "\u001b[2m\u001b[33m(raylet, ip=172.31.29.141)\u001b[0m     std::_Function_handler<>::_M_invoke()\n",
      "\u001b[2m\u001b[33m(raylet, ip=172.31.29.141)\u001b[0m     EventTracker::RecordExecution()\n",
      "\u001b[2m\u001b[33m(raylet, ip=172.31.29.141)\u001b[0m     std::_Function_handler<>::_M_invoke()\n",
      "\u001b[2m\u001b[33m(raylet, ip=172.31.29.141)\u001b[0m     boost::asio::detail::completion_handler<>::do_complete()\n",
      "\u001b[2m\u001b[33m(raylet, ip=172.31.29.141)\u001b[0m     boost::asio::detail::scheduler::do_run_one()\n",
      "\u001b[2m\u001b[33m(raylet, ip=172.31.29.141)\u001b[0m     boost::asio::detail::scheduler::run()\n",
      "\u001b[2m\u001b[33m(raylet, ip=172.31.29.141)\u001b[0m     boost::asio::io_context::run()\n",
      "\u001b[2m\u001b[33m(raylet, ip=172.31.29.141)\u001b[0m     main\n",
      "\u001b[2m\u001b[33m(raylet, ip=172.31.29.141)\u001b[0m     __libc_start_main\n",
      "\u001b[2m\u001b[33m(raylet, ip=172.31.29.141)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=gcs_server)\u001b[0m [2022-07-06 12:16:23,750 E 29692 29692] (gcs_server) gcs_server.cc:283: Failed to get the resource load: GrpcUnavailable: RPC Error message: Socket closed; RPC Error details: \n",
      "\u001b[2m\u001b[36m(pid=gcs_server)\u001b[0m [2022-07-06 12:16:23,750 E 29692 29692] (gcs_server) gcs_server.cc:283: Failed to get the resource load: GrpcUnavailable: RPC Error message: Socket closed; RPC Error details: \n",
      "\u001b[2m\u001b[36m(pid=gcs_server)\u001b[0m [2022-07-06 12:16:23,750 E 29692 29692] (gcs_server) gcs_server.cc:283: Failed to get the resource load: GrpcUnavailable: RPC Error message: Socket closed; RPC Error details: \n",
      "\u001b[2m\u001b[36m(pid=gcs_server)\u001b[0m [2022-07-06 12:16:23,750 E 29692 29692] (gcs_server) gcs_server.cc:283: Failed to get the resource load: GrpcUnavailable: RPC Error message: Socket closed; RPC Error details: \n",
      "\u001b[2m\u001b[36m(pid=gcs_server)\u001b[0m [2022-07-06 12:16:23,750 E 29692 29692] (gcs_server) gcs_server.cc:283: Failed to get the resource load: GrpcUnavailable: RPC Error message: Socket closed; RPC Error details: \n",
      "\u001b[2m\u001b[36m(pid=gcs_server)\u001b[0m [2022-07-06 12:16:23,750 E 29692 29692] (gcs_server) gcs_server.cc:283: Failed to get the resource load: GrpcUnavailable: RPC Error message: Socket closed; RPC Error details: \n",
      "\u001b[2m\u001b[36m(pid=gcs_server)\u001b[0m [2022-07-06 12:16:23,750 E 29692 29692] (gcs_server) gcs_server.cc:283: Failed to get the resource load: GrpcUnavailable: RPC Error message: Socket closed; RPC Error details: \n",
      "\u001b[2m\u001b[36m(pid=gcs_server)\u001b[0m [2022-07-06 12:16:23,750 E 29692 29692] (gcs_server) gcs_server.cc:283: Failed to get the resource load: GrpcUnavailable: RPC Error message: Socket closed; RPC Error details: \n",
      "\u001b[2m\u001b[36m(pid=gcs_server)\u001b[0m [2022-07-06 12:16:23,750 E 29692 29692] (gcs_server) gcs_server.cc:283: Failed to get the resource load: GrpcUnavailable: RPC Error message: Socket closed; RPC Error details: \n",
      "\u001b[2m\u001b[36m(pid=gcs_server)\u001b[0m [2022-07-06 12:16:23,751 E 29692 29692] (gcs_server) gcs_server.cc:283: Failed to get the resource load: GrpcUnavailable: RPC Error message: Socket closed; RPC Error details: \n",
      "\u001b[2m\u001b[36m(pid=gcs_server)\u001b[0m [2022-07-06 12:16:23,751 E 29692 29692] (gcs_server) gcs_server.cc:283: Failed to get the resource load: GrpcUnavailable: RPC Error message: Socket closed; RPC Error details: \n",
      "\u001b[2m\u001b[36m(pid=gcs_server)\u001b[0m [2022-07-06 12:16:23,751 E 29692 29692] (gcs_server) gcs_server.cc:283: Failed to get the resource load: GrpcUnavailable: RPC Error message: Socket closed; RPC Error details: \n",
      "\u001b[2m\u001b[36m(pid=gcs_server)\u001b[0m [2022-07-06 12:16:23,751 E 29692 29692] (gcs_server) gcs_server.cc:283: Failed to get the resource load: GrpcUnavailable: RPC Error message: Socket closed; RPC Error details: \n",
      "\u001b[2m\u001b[36m(pid=gcs_server)\u001b[0m [2022-07-06 12:16:23,751 E 29692 29692] (gcs_server) gcs_server.cc:283: Failed to get the resource load: GrpcUnavailable: RPC Error message: Socket closed; RPC Error details: \n",
      "\u001b[2m\u001b[36m(pid=gcs_server)\u001b[0m [2022-07-06 12:16:23,751 E 29692 29692] (gcs_server) gcs_server.cc:283: Failed to get the resource load: GrpcUnavailable: RPC Error message: Socket closed; RPC Error details: \n",
      "\u001b[2m\u001b[36m(pid=gcs_server)\u001b[0m [2022-07-06 12:16:23,751 E 29692 29692] (gcs_server) gcs_server.cc:283: Failed to get the resource load: GrpcUnavailable: RPC Error message: Socket closed; RPC Error details: \n",
      "\u001b[2m\u001b[36m(pid=gcs_server)\u001b[0m [2022-07-06 12:16:23,751 E 29692 29692] (gcs_server) gcs_server.cc:283: Failed to get the resource load: GrpcUnavailable: RPC Error message: Socket closed; RPC Error details: \n",
      "\u001b[2m\u001b[36m(pid=gcs_server)\u001b[0m [2022-07-06 12:16:23,751 E 29692 29692] (gcs_server) gcs_server.cc:283: Failed to get the resource load: GrpcUnavailable: RPC Error message: Socket closed; RPC Error details: \n",
      "\u001b[2m\u001b[36m(pid=gcs_server)\u001b[0m [2022-07-06 12:16:23,751 E 29692 29692] (gcs_server) gcs_server.cc:283: Failed to get the resource load: GrpcUnavailable: RPC Error message: Socket closed; RPC Error details: \n",
      "\u001b[2m\u001b[36m(pid=gcs_server)\u001b[0m [2022-07-06 12:16:23,751 E 29692 29692] (gcs_server) gcs_server.cc:283: Failed to get the resource load: GrpcUnavailable: RPC Error message: Socket closed; RPC Error details: \n",
      "\u001b[2m\u001b[36m(pid=gcs_server)\u001b[0m [2022-07-06 12:16:23,751 E 29692 29692] (gcs_server) gcs_server.cc:283: Failed to get the resource load: GrpcUnavailable: RPC Error message: Socket closed; RPC Error details: \n",
      "\u001b[2m\u001b[36m(pid=gcs_server)\u001b[0m [2022-07-06 12:16:23,751 E 29692 29692] (gcs_server) gcs_server.cc:283: Failed to get the resource load: GrpcUnavailable: RPC Error message: Socket closed; RPC Error details: \n",
      "\u001b[2m\u001b[36m(pid=gcs_server)\u001b[0m [2022-07-06 12:16:23,751 E 29692 29692] (gcs_server) gcs_server.cc:283: Failed to get the resource load: GrpcUnavailable: RPC Error message: Socket closed; RPC Error details: \n",
      "\u001b[2m\u001b[36m(pid=gcs_server)\u001b[0m [2022-07-06 12:16:23,752 E 29692 29692] (gcs_server) gcs_server.cc:283: Failed to get the resource load: GrpcUnavailable: RPC Error message: Socket closed; RPC Error details: \n",
      "\u001b[2m\u001b[36m(pid=gcs_server)\u001b[0m [2022-07-06 12:16:23,752 E 29692 29692] (gcs_server) gcs_server.cc:283: Failed to get the resource load: GrpcUnavailable: RPC Error message: Socket closed; RPC Error details: \n",
      "\u001b[2m\u001b[36m(pid=gcs_server)\u001b[0m [2022-07-06 12:16:23,752 E 29692 29692] (gcs_server) gcs_server.cc:283: Failed to get the resource load: GrpcUnavailable: RPC Error message: Socket closed; RPC Error details: \n",
      "\u001b[2m\u001b[36m(pid=gcs_server)\u001b[0m [2022-07-06 12:16:23,752 E 29692 29692] (gcs_server) gcs_server.cc:283: Failed to get the resource load: GrpcUnavailable: RPC Error message: Socket closed; RPC Error details: \n",
      "\u001b[2m\u001b[36m(pid=gcs_server)\u001b[0m [2022-07-06 12:16:23,752 E 29692 29692] (gcs_server) gcs_server.cc:283: Failed to get the resource load: GrpcUnavailable: RPC Error message: Socket closed; RPC Error details: \n",
      "\u001b[2m\u001b[36m(pid=gcs_server)\u001b[0m [2022-07-06 12:16:23,752 E 29692 29692] (gcs_server) gcs_server.cc:283: Failed to get the resource load: GrpcUnavailable: RPC Error message: Socket closed; RPC Error details: \n",
      "\u001b[2m\u001b[36m(pid=gcs_server)\u001b[0m [2022-07-06 12:16:23,752 E 29692 29692] (gcs_server) gcs_server.cc:283: Failed to get the resource load: GrpcUnavailable: RPC Error message: Socket closed; RPC Error details: \n",
      "\u001b[2m\u001b[36m(pid=gcs_server)\u001b[0m [2022-07-06 12:16:23,752 E 29692 29692] (gcs_server) gcs_server.cc:283: Failed to get the resource load: GrpcUnavailable: RPC Error message: Socket closed; RPC Error details: \n",
      "\u001b[2m\u001b[36m(pid=gcs_server)\u001b[0m [2022-07-06 12:16:23,752 E 29692 29692] (gcs_server) gcs_server.cc:283: Failed to get the resource load: GrpcUnavailable: RPC Error message: Socket closed; RPC Error details: \n",
      "\u001b[2m\u001b[36m(pid=gcs_server)\u001b[0m [2022-07-06 12:16:23,752 E 29692 29692] (gcs_server) gcs_server.cc:283: Failed to get the resource load: GrpcUnavailable: RPC Error message: Socket closed; RPC Error details: \n",
      "\u001b[2m\u001b[36m(pid=gcs_server)\u001b[0m [2022-07-06 12:16:23,752 E 29692 29692] (gcs_server) gcs_server.cc:283: Failed to get the resource load: GrpcUnavailable: RPC Error message: Socket closed; RPC Error details: \n",
      "\u001b[2m\u001b[36m(pid=gcs_server)\u001b[0m [2022-07-06 12:16:23,752 E 29692 29692] (gcs_server) gcs_server.cc:283: Failed to get the resource load: GrpcUnavailable: RPC Error message: Socket closed; RPC Error details: \n",
      "\u001b[2m\u001b[36m(pid=gcs_server)\u001b[0m [2022-07-06 12:16:23,752 E 29692 29692] (gcs_server) gcs_server.cc:283: Failed to get the resource load: GrpcUnavailable: RPC Error message: Socket closed; RPC Error details: \n",
      "\u001b[2m\u001b[36m(pid=gcs_server)\u001b[0m [2022-07-06 12:16:23,752 E 29692 29692] (gcs_server) gcs_server.cc:283: Failed to get the resource load: GrpcUnavailable: RPC Error message: Socket closed; RPC Error details: \n",
      "\u001b[2m\u001b[36m(pid=gcs_server)\u001b[0m [2022-07-06 12:16:23,752 E 29692 29692] (gcs_server) gcs_server.cc:283: Failed to get the resource load: GrpcUnavailable: RPC Error message: Socket closed; RPC Error details: \n",
      "\u001b[2m\u001b[36m(pid=gcs_server)\u001b[0m [2022-07-06 12:16:23,752 E 29692 29692] (gcs_server) gcs_server.cc:283: Failed to get the resource load: GrpcUnavailable: RPC Error message: Socket closed; RPC Error details: \n",
      "\u001b[2m\u001b[36m(pid=gcs_server)\u001b[0m [2022-07-06 12:16:23,752 E 29692 29692] (gcs_server) gcs_server.cc:283: Failed to get the resource load: GrpcUnavailable: RPC Error message: Socket closed; RPC Error details: \n",
      "\u001b[2m\u001b[36m(pid=gcs_server)\u001b[0m [2022-07-06 12:16:23,753 E 29692 29692] (gcs_server) gcs_server.cc:283: Failed to get the resource load: GrpcUnavailable: RPC Error message: Socket closed; RPC Error details: \n",
      "\u001b[2m\u001b[36m(pid=gcs_server)\u001b[0m [2022-07-06 12:16:23,753 E 29692 29692] (gcs_server) gcs_server.cc:283: Failed to get the resource load: GrpcUnavailable: RPC Error message: Socket closed; RPC Error details: \n",
      "\u001b[2m\u001b[36m(pid=gcs_server)\u001b[0m [2022-07-06 12:16:23,753 E 29692 29692] (gcs_server) gcs_server.cc:283: Failed to get the resource load: GrpcUnavailable: RPC Error message: Socket closed; RPC Error details: \n",
      "\u001b[2m\u001b[36m(pid=gcs_server)\u001b[0m [2022-07-06 12:16:23,753 E 29692 29692] (gcs_server) gcs_server.cc:283: Failed to get the resource load: GrpcUnavailable: RPC Error message: Socket closed; RPC Error details: \n",
      "\u001b[2m\u001b[36m(pid=gcs_server)\u001b[0m [2022-07-06 12:16:23,753 E 29692 29692] (gcs_server) gcs_server.cc:283: Failed to get the resource load: GrpcUnavailable: RPC Error message: Socket closed; RPC Error details: \n",
      "\u001b[2m\u001b[36m(pid=gcs_server)\u001b[0m [2022-07-06 12:16:23,753 E 29692 29692] (gcs_server) gcs_server.cc:283: Failed to get the resource load: GrpcUnavailable: RPC Error message: Socket closed; RPC Error details: \n",
      "\u001b[2m\u001b[36m(pid=gcs_server)\u001b[0m [2022-07-06 12:16:23,753 E 29692 29692] (gcs_server) gcs_server.cc:283: Failed to get the resource load: GrpcUnavailable: RPC Error message: Socket closed; RPC Error details: \n",
      "\u001b[2m\u001b[36m(pid=gcs_server)\u001b[0m [2022-07-06 12:16:23,753 E 29692 29692] (gcs_server) gcs_server.cc:283: Failed to get the resource load: GrpcUnavailable: RPC Error message: Socket closed; RPC Error details: \n",
      "\u001b[2m\u001b[36m(pid=gcs_server)\u001b[0m [2022-07-06 12:16:23,753 E 29692 29692] (gcs_server) gcs_server.cc:283: Failed to get the resource load: GrpcUnavailable: RPC Error message: Socket closed; RPC Error details: \n"
     ]
    },
    {
     "ename": "RayTaskError(MemoryError)",
     "evalue": "\u001b[36mray::deploy_ray_func()\u001b[39m (pid=26917, ip=172.31.29.141)\n  File \"/home/emr-notebook/.local/lib/python3.7/site-packages/modin/core/execution/ray/common/task_wrapper.py\", line 40, in deploy_ray_func\n  File \"/tmp/ray/session_2022-07-06_02-59-12_340846_29218/runtime_resources/pip/11ec394aa27dc2f92256e9847ec87567ef3cace5/virtualenv/lib/python3.7/site-packages/modin/core/storage_formats/pandas/parsers.py\", line 622, in parse\n    df = pandas.read_parquet(fname, **kwargs)\n  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 500, in read_parquet\n    **kwargs,\n  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 240, in read\n    path_or_handle, columns=columns, **kwargs\n  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1942, in read_table\n    use_pandas_metadata=use_pandas_metadata)\n  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1778, in read\n    use_threads=use_threads\n  File \"pyarrow/_dataset.pyx\", line 491, in pyarrow._dataset.Dataset.to_table\n  File \"pyarrow/_dataset.pyx\", line 3235, in pyarrow._dataset.Scanner.to_table\n  File \"pyarrow/error.pxi\", line 143, in pyarrow.lib.pyarrow_internal_check_status\n  File \"/usr/local/lib/python3.7/site-packages/fsspec/spec.py\", line 1578, in read\n    out = self.cache._fetch(self.loc, self.loc + length)\n  File \"/usr/local/lib/python3.7/site-packages/fsspec/caching.py\", line 399, in _fetch\n    out = self.cache[offset : offset + end - start]\nMemoryError",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mRayTaskError(MemoryError)\u001b[0m                 Traceback (most recent call last)",
      "\u001b[0;32m<timed exec>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n",
      "\u001b[0;32m~/.local/lib/python3.7/site-packages/modin/pandas/io.py\u001b[0m in \u001b[0;36mread_parquet\u001b[0;34m(path, engine, columns, storage_options, use_nullable_dtypes, **kwargs)\u001b[0m\n\u001b[1;32m    220\u001b[0m             \u001b[0mstorage_options\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mstorage_options\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    221\u001b[0m             \u001b[0muse_nullable_dtypes\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0muse_nullable_dtypes\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 222\u001b[0;31m             \u001b[0;34m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    223\u001b[0m         )\n\u001b[1;32m    224\u001b[0m     )\n",
      "\u001b[0;32m~/.local/lib/python3.7/site-packages/modin/core/execution/dispatching/factories/dispatcher.py\u001b[0m in \u001b[0;36mread_parquet\u001b[0;34m(cls, **kwargs)\u001b[0m\n\u001b[1;32m    173\u001b[0m     \u001b[0;34m@\u001b[0m\u001b[0m_inherit_docstrings\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mfactories\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mBaseFactory\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_read_parquet\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    174\u001b[0m     \u001b[0;32mdef\u001b[0m \u001b[0mread_parquet\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mcls\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 175\u001b[0;31m         \u001b[0;32mreturn\u001b[0m \u001b[0mcls\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m__factory\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_read_parquet\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    176\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    177\u001b[0m     \u001b[0;34m@\u001b[0m\u001b[0mclassmethod\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/.local/lib/python3.7/site-packages/modin/core/execution/dispatching/factories/factories.py\u001b[0m in \u001b[0;36m_read_parquet\u001b[0;34m(cls, **kwargs)\u001b[0m\n\u001b[1;32m    195\u001b[0m     )\n\u001b[1;32m    196\u001b[0m     \u001b[0;32mdef\u001b[0m \u001b[0m_read_parquet\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mcls\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 197\u001b[0;31m         \u001b[0;32mreturn\u001b[0m \u001b[0mcls\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mio_cls\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mread_parquet\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    198\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    199\u001b[0m     \u001b[0;34m@\u001b[0m\u001b[0mclassmethod\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/.local/lib/python3.7/site-packages/modin/core/io/file_dispatcher.py\u001b[0m in \u001b[0;36mread\u001b[0;34m(cls, *args, **kwargs)\u001b[0m\n\u001b[1;32m    149\u001b[0m         \u001b[0mpostprocessing\u001b[0m \u001b[0mwork\u001b[0m \u001b[0mon\u001b[0m \u001b[0mthe\u001b[0m \u001b[0mresulting\u001b[0m \u001b[0mquery_compiler\u001b[0m \u001b[0mobject\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    150\u001b[0m         \"\"\"\n\u001b[0;32m--> 151\u001b[0;31m         \u001b[0mquery_compiler\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mcls\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_read\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m*\u001b[0m\u001b[0margs\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    152\u001b[0m         \u001b[0;31m# TODO (devin-petersohn): Make this section more general for non-pandas kernel\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    153\u001b[0m         \u001b[0;31m# implementations.\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/.local/lib/python3.7/site-packages/modin/core/io/column_stores/parquet_dispatcher.py\u001b[0m in \u001b[0;36m_read\u001b[0;34m(cls, path, engine, columns, **kwargs)\u001b[0m\n\u001b[1;32m    100\u001b[0m                 \u001b[0mcolumn_names\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m[\u001b[0m\u001b[0mc\u001b[0m \u001b[0;32mfor\u001b[0m \u001b[0mc\u001b[0m \u001b[0;32min\u001b[0m \u001b[0mcolumn_names\u001b[0m \u001b[0;32mif\u001b[0m \u001b[0mc\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0;32min\u001b[0m \u001b[0mindex_columns\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    101\u001b[0m             \u001b[0mcolumns\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m[\u001b[0m\u001b[0mname\u001b[0m \u001b[0;32mfor\u001b[0m \u001b[0mname\u001b[0m \u001b[0;32min\u001b[0m \u001b[0mcolumn_names\u001b[0m \u001b[0;32mif\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0mPQ_INDEX_REGEX\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mmatch\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mname\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 102\u001b[0;31m         \u001b[0;32mreturn\u001b[0m \u001b[0mcls\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mbuild_query_compiler\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mpath\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mcolumns\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[0;32m~/.local/lib/python3.7/site-packages/modin/core/io/column_stores/column_store_dispatcher.py\u001b[0m in \u001b[0;36mbuild_query_compiler\u001b[0;34m(cls, path, columns, **kwargs)\u001b[0m\n\u001b[1;32m    218\u001b[0m         \u001b[0mindex\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mrow_lens\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mcls\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mbuild_index\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mpartition_ids\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    219\u001b[0m         \u001b[0mremote_parts\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mcls\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mbuild_partition\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mpartition_ids\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m-\u001b[0m\u001b[0;36m2\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mrow_lens\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mcolumn_widths\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 220\u001b[0;31m         \u001b[0mdtypes\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mcls\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mbuild_dtypes\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mpartition_ids\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m-\u001b[0m\u001b[0;36m1\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mcolumns\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    221\u001b[0m         new_query_compiler = cls.query_compiler_cls(\n\u001b[1;32m    222\u001b[0m             cls.frame_cls(\n",
      "\u001b[0;32m~/.local/lib/python3.7/site-packages/modin/core/io/column_stores/column_store_dispatcher.py\u001b[0m in \u001b[0;36mbuild_dtypes\u001b[0;34m(cls, partition_ids, columns)\u001b[0m\n\u001b[1;32m    191\u001b[0m             \u001b[0mSeries\u001b[0m \u001b[0;32mwith\u001b[0m \u001b[0mdtypes\u001b[0m \u001b[0;32mfor\u001b[0m \u001b[0mcolumns\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    192\u001b[0m         \"\"\"\n\u001b[0;32m--> 193\u001b[0;31m         \u001b[0mdtypes\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mpandas\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mconcat\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mcls\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mmaterialize\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mlist\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mpartition_ids\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0maxis\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;36m0\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    194\u001b[0m         \u001b[0mdtypes\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mindex\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mcolumns\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    195\u001b[0m         \u001b[0;32mreturn\u001b[0m \u001b[0mdtypes\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/.local/lib/python3.7/site-packages/modin/core/execution/ray/common/task_wrapper.py\u001b[0m in \u001b[0;36mmaterialize\u001b[0;34m(cls, obj_id)\u001b[0m\n\u001b[1;32m     80\u001b[0m             \u001b[0mWhatever\u001b[0m \u001b[0mwas\u001b[0m \u001b[0midentified\u001b[0m \u001b[0mby\u001b[0m\u001b[0;31m \u001b[0m\u001b[0;31m`\u001b[0m\u001b[0mobj_id\u001b[0m\u001b[0;31m`\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     81\u001b[0m         \"\"\"\n\u001b[0;32m---> 82\u001b[0;31m         \u001b[0;32mreturn\u001b[0m \u001b[0mray\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mget\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mobj_id\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[0;32m/emr/notebook-env/lib/python3.7/site-packages/ray/_private/client_mode_hook.py\u001b[0m in \u001b[0;36mwrapper\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m    102\u001b[0m             \u001b[0;31m# we only convert init function if RAY_CLIENT_MODE=1\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    103\u001b[0m             \u001b[0;32mif\u001b[0m \u001b[0mfunc\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m__name__\u001b[0m \u001b[0;34m!=\u001b[0m \u001b[0;34m\"init\"\u001b[0m \u001b[0;32mor\u001b[0m \u001b[0mis_client_mode_enabled_by_default\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 104\u001b[0;31m                 \u001b[0;32mreturn\u001b[0m \u001b[0mgetattr\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mray\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mfunc\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m__name__\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m*\u001b[0m\u001b[0margs\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    105\u001b[0m         \u001b[0;32mreturn\u001b[0m \u001b[0mfunc\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m*\u001b[0m\u001b[0margs\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    106\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/emr/notebook-env/lib/python3.7/site-packages/ray/util/client/api.py\u001b[0m in \u001b[0;36mget\u001b[0;34m(self, vals, timeout)\u001b[0m\n\u001b[1;32m     42\u001b[0m             \u001b[0mtimeout\u001b[0m\u001b[0;34m:\u001b[0m \u001b[0mOptional\u001b[0m \u001b[0mtimeout\u001b[0m \u001b[0;32min\u001b[0m \u001b[0mmilliseconds\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     43\u001b[0m         \"\"\"\n\u001b[0;32m---> 44\u001b[0;31m         \u001b[0;32mreturn\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mworker\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mget\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mvals\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mtimeout\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mtimeout\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     45\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     46\u001b[0m     \u001b[0;32mdef\u001b[0m \u001b[0mput\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m*\u001b[0m\u001b[0margs\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/emr/notebook-env/lib/python3.7/site-packages/ray/util/client/worker.py\u001b[0m in \u001b[0;36mget\u001b[0;34m(self, vals, timeout)\u001b[0m\n\u001b[1;32m    436\u001b[0m                 \u001b[0mop_timeout\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mmax_blocking_operation_time\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    437\u001b[0m             \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 438\u001b[0;31m                 \u001b[0mres\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_get\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mto_get\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mop_timeout\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    439\u001b[0m                 \u001b[0;32mbreak\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    440\u001b[0m             \u001b[0;32mexcept\u001b[0m \u001b[0mGetTimeoutError\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/emr/notebook-env/lib/python3.7/site-packages/ray/util/client/worker.py\u001b[0m in \u001b[0;36m_get\u001b[0;34m(self, ref, timeout)\u001b[0m\n\u001b[1;32m    464\u001b[0m                         \u001b[0mlogger\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mexception\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"Failed to deserialize {}\"\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mformat\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mchunk\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0merror\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    465\u001b[0m                         \u001b[0;32mraise\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 466\u001b[0;31m                     \u001b[0;32mraise\u001b[0m \u001b[0merr\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    467\u001b[0m                 if chunk.total_size > OBJECT_TRANSFER_WARNING_SIZE and log_once(\n\u001b[1;32m    468\u001b[0m                     \u001b[0;34m\"client_object_transfer_size_warning\"\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mRayTaskError(MemoryError)\u001b[0m: \u001b[36mray::deploy_ray_func()\u001b[39m (pid=26917, ip=172.31.29.141)\n  File \"/home/emr-notebook/.local/lib/python3.7/site-packages/modin/core/execution/ray/common/task_wrapper.py\", line 40, in deploy_ray_func\n  File \"/tmp/ray/session_2022-07-06_02-59-12_340846_29218/runtime_resources/pip/11ec394aa27dc2f92256e9847ec87567ef3cace5/virtualenv/lib/python3.7/site-packages/modin/core/storage_formats/pandas/parsers.py\", line 622, in parse\n    df = pandas.read_parquet(fname, **kwargs)\n  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 500, in read_parquet\n    **kwargs,\n  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 240, in read\n    path_or_handle, columns=columns, **kwargs\n  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1942, in read_table\n    use_pandas_metadata=use_pandas_metadata)\n  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1778, in read\n    use_threads=use_threads\n  File \"pyarrow/_dataset.pyx\", line 491, in pyarrow._dataset.Dataset.to_table\n  File \"pyarrow/_dataset.pyx\", line 3235, in pyarrow._dataset.Scanner.to_table\n  File \"pyarrow/error.pxi\", line 143, in pyarrow.lib.pyarrow_internal_check_status\n  File \"/usr/local/lib/python3.7/site-packages/fsspec/spec.py\", line 1578, in read\n    out = self.cache._fetch(self.loc, self.loc + length)\n  File \"/usr/local/lib/python3.7/site-packages/fsspec/caching.py\", line 399, in _fetch\n    out = self.cache[offset : offset + end - start]\nMemoryError"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::deploy_ray_func()\u001b[39m (pid=24638, ip=172.31.27.60)\n",
      "  File \"/home/emr-notebook/.local/lib/python3.7/site-packages/modin/core/execution/ray/common/task_wrapper.py\", line 40, in deploy_ray_func\n",
      "  File \"/tmp/ray/session_2022-07-06_02-59-12_340846_29218/runtime_resources/pip/11ec394aa27dc2f92256e9847ec87567ef3cace5/virtualenv/lib/python3.7/site-packages/modin/core/storage_formats/pandas/parsers.py\", line 622, in parse\n",
      "    df = pandas.read_parquet(fname, **kwargs)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 500, in read_parquet\n",
      "    **kwargs,\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 240, in read\n",
      "    path_or_handle, columns=columns, **kwargs\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1942, in read_table\n",
      "    use_pandas_metadata=use_pandas_metadata)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1778, in read\n",
      "    use_threads=use_threads\n",
      "  File \"pyarrow/_dataset.pyx\", line 491, in pyarrow._dataset.Dataset.to_table\n",
      "  File \"pyarrow/_dataset.pyx\", line 3235, in pyarrow._dataset.Scanner.to_table\n",
      "  File \"pyarrow/error.pxi\", line 143, in pyarrow.lib.pyarrow_internal_check_status\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/spec.py\", line 1578, in read\n",
      "    out = self.cache._fetch(self.loc, self.loc + length)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/caching.py\", line 399, in _fetch\n",
      "    out = self.cache[offset : offset + end - start]\n",
      "MemoryError\n",
      "Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::deploy_ray_func()\u001b[39m (pid=24638, ip=172.31.27.60)\n",
      "  File \"/home/emr-notebook/.local/lib/python3.7/site-packages/modin/core/execution/ray/common/task_wrapper.py\", line 40, in deploy_ray_func\n",
      "  File \"/tmp/ray/session_2022-07-06_02-59-12_340846_29218/runtime_resources/pip/11ec394aa27dc2f92256e9847ec87567ef3cace5/virtualenv/lib/python3.7/site-packages/modin/core/storage_formats/pandas/parsers.py\", line 622, in parse\n",
      "    df = pandas.read_parquet(fname, **kwargs)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 500, in read_parquet\n",
      "    **kwargs,\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 240, in read\n",
      "    path_or_handle, columns=columns, **kwargs\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1942, in read_table\n",
      "    use_pandas_metadata=use_pandas_metadata)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1778, in read\n",
      "    use_threads=use_threads\n",
      "  File \"pyarrow/_dataset.pyx\", line 491, in pyarrow._dataset.Dataset.to_table\n",
      "  File \"pyarrow/_dataset.pyx\", line 3235, in pyarrow._dataset.Scanner.to_table\n",
      "  File \"pyarrow/error.pxi\", line 143, in pyarrow.lib.pyarrow_internal_check_status\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/spec.py\", line 1578, in read\n",
      "    out = self.cache._fetch(self.loc, self.loc + length)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/caching.py\", line 399, in _fetch\n",
      "    out = self.cache[offset : offset + end - start]\n",
      "MemoryError\n",
      "Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::deploy_ray_func()\u001b[39m (pid=24638, ip=172.31.27.60)\n",
      "  File \"/home/emr-notebook/.local/lib/python3.7/site-packages/modin/core/execution/ray/common/task_wrapper.py\", line 40, in deploy_ray_func\n",
      "  File \"/tmp/ray/session_2022-07-06_02-59-12_340846_29218/runtime_resources/pip/11ec394aa27dc2f92256e9847ec87567ef3cace5/virtualenv/lib/python3.7/site-packages/modin/core/storage_formats/pandas/parsers.py\", line 622, in parse\n",
      "    df = pandas.read_parquet(fname, **kwargs)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 500, in read_parquet\n",
      "    **kwargs,\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 240, in read\n",
      "    path_or_handle, columns=columns, **kwargs\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1942, in read_table\n",
      "    use_pandas_metadata=use_pandas_metadata)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1778, in read\n",
      "    use_threads=use_threads\n",
      "  File \"pyarrow/_dataset.pyx\", line 491, in pyarrow._dataset.Dataset.to_table\n",
      "  File \"pyarrow/_dataset.pyx\", line 3235, in pyarrow._dataset.Scanner.to_table\n",
      "  File \"pyarrow/error.pxi\", line 143, in pyarrow.lib.pyarrow_internal_check_status\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/spec.py\", line 1578, in read\n",
      "    out = self.cache._fetch(self.loc, self.loc + length)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/caching.py\", line 399, in _fetch\n",
      "    out = self.cache[offset : offset + end - start]\n",
      "MemoryError\n",
      "Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::deploy_ray_func()\u001b[39m (pid=24638, ip=172.31.27.60)\n",
      "  File \"/home/emr-notebook/.local/lib/python3.7/site-packages/modin/core/execution/ray/common/task_wrapper.py\", line 40, in deploy_ray_func\n",
      "  File \"/tmp/ray/session_2022-07-06_02-59-12_340846_29218/runtime_resources/pip/11ec394aa27dc2f92256e9847ec87567ef3cace5/virtualenv/lib/python3.7/site-packages/modin/core/storage_formats/pandas/parsers.py\", line 622, in parse\n",
      "    df = pandas.read_parquet(fname, **kwargs)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 500, in read_parquet\n",
      "    **kwargs,\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 240, in read\n",
      "    path_or_handle, columns=columns, **kwargs\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1942, in read_table\n",
      "    use_pandas_metadata=use_pandas_metadata)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1778, in read\n",
      "    use_threads=use_threads\n",
      "  File \"pyarrow/_dataset.pyx\", line 491, in pyarrow._dataset.Dataset.to_table\n",
      "  File \"pyarrow/_dataset.pyx\", line 3235, in pyarrow._dataset.Scanner.to_table\n",
      "  File \"pyarrow/error.pxi\", line 143, in pyarrow.lib.pyarrow_internal_check_status\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/spec.py\", line 1578, in read\n",
      "    out = self.cache._fetch(self.loc, self.loc + length)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/caching.py\", line 399, in _fetch\n",
      "    out = self.cache[offset : offset + end - start]\n",
      "MemoryError\n",
      "Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::deploy_ray_func()\u001b[39m (pid=24638, ip=172.31.27.60)\n",
      "  File \"/home/emr-notebook/.local/lib/python3.7/site-packages/modin/core/execution/ray/common/task_wrapper.py\", line 40, in deploy_ray_func\n",
      "  File \"/tmp/ray/session_2022-07-06_02-59-12_340846_29218/runtime_resources/pip/11ec394aa27dc2f92256e9847ec87567ef3cace5/virtualenv/lib/python3.7/site-packages/modin/core/storage_formats/pandas/parsers.py\", line 622, in parse\n",
      "    df = pandas.read_parquet(fname, **kwargs)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 500, in read_parquet\n",
      "    **kwargs,\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 240, in read\n",
      "    path_or_handle, columns=columns, **kwargs\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1942, in read_table\n",
      "    use_pandas_metadata=use_pandas_metadata)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1778, in read\n",
      "    use_threads=use_threads\n",
      "  File \"pyarrow/_dataset.pyx\", line 491, in pyarrow._dataset.Dataset.to_table\n",
      "  File \"pyarrow/_dataset.pyx\", line 3235, in pyarrow._dataset.Scanner.to_table\n",
      "  File \"pyarrow/error.pxi\", line 143, in pyarrow.lib.pyarrow_internal_check_status\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/spec.py\", line 1578, in read\n",
      "    out = self.cache._fetch(self.loc, self.loc + length)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/caching.py\", line 399, in _fetch\n",
      "    out = self.cache[offset : offset + end - start]\n",
      "MemoryError\n",
      "Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::deploy_ray_func()\u001b[39m (pid=24638, ip=172.31.27.60)\n",
      "  File \"/home/emr-notebook/.local/lib/python3.7/site-packages/modin/core/execution/ray/common/task_wrapper.py\", line 40, in deploy_ray_func\n",
      "  File \"/tmp/ray/session_2022-07-06_02-59-12_340846_29218/runtime_resources/pip/11ec394aa27dc2f92256e9847ec87567ef3cace5/virtualenv/lib/python3.7/site-packages/modin/core/storage_formats/pandas/parsers.py\", line 622, in parse\n",
      "    df = pandas.read_parquet(fname, **kwargs)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 500, in read_parquet\n",
      "    **kwargs,\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 240, in read\n",
      "    path_or_handle, columns=columns, **kwargs\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1942, in read_table\n",
      "    use_pandas_metadata=use_pandas_metadata)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1778, in read\n",
      "    use_threads=use_threads\n",
      "  File \"pyarrow/_dataset.pyx\", line 491, in pyarrow._dataset.Dataset.to_table\n",
      "  File \"pyarrow/_dataset.pyx\", line 3235, in pyarrow._dataset.Scanner.to_table\n",
      "  File \"pyarrow/error.pxi\", line 143, in pyarrow.lib.pyarrow_internal_check_status\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/spec.py\", line 1578, in read\n",
      "    out = self.cache._fetch(self.loc, self.loc + length)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/caching.py\", line 399, in _fetch\n",
      "    out = self.cache[offset : offset + end - start]\n",
      "MemoryError\n",
      "Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::deploy_ray_func()\u001b[39m (pid=24638, ip=172.31.27.60)\n",
      "  File \"/home/emr-notebook/.local/lib/python3.7/site-packages/modin/core/execution/ray/common/task_wrapper.py\", line 40, in deploy_ray_func\n",
      "  File \"/tmp/ray/session_2022-07-06_02-59-12_340846_29218/runtime_resources/pip/11ec394aa27dc2f92256e9847ec87567ef3cace5/virtualenv/lib/python3.7/site-packages/modin/core/storage_formats/pandas/parsers.py\", line 622, in parse\n",
      "    df = pandas.read_parquet(fname, **kwargs)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 500, in read_parquet\n",
      "    **kwargs,\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 240, in read\n",
      "    path_or_handle, columns=columns, **kwargs\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1942, in read_table\n",
      "    use_pandas_metadata=use_pandas_metadata)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1778, in read\n",
      "    use_threads=use_threads\n",
      "  File \"pyarrow/_dataset.pyx\", line 491, in pyarrow._dataset.Dataset.to_table\n",
      "  File \"pyarrow/_dataset.pyx\", line 3235, in pyarrow._dataset.Scanner.to_table\n",
      "  File \"pyarrow/error.pxi\", line 143, in pyarrow.lib.pyarrow_internal_check_status\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/spec.py\", line 1578, in read\n",
      "    out = self.cache._fetch(self.loc, self.loc + length)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/caching.py\", line 399, in _fetch\n",
      "    out = self.cache[offset : offset + end - start]\n",
      "MemoryError\n",
      "Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::deploy_ray_func()\u001b[39m (pid=24638, ip=172.31.27.60)\n",
      "  File \"/home/emr-notebook/.local/lib/python3.7/site-packages/modin/core/execution/ray/common/task_wrapper.py\", line 40, in deploy_ray_func\n",
      "  File \"/tmp/ray/session_2022-07-06_02-59-12_340846_29218/runtime_resources/pip/11ec394aa27dc2f92256e9847ec87567ef3cace5/virtualenv/lib/python3.7/site-packages/modin/core/storage_formats/pandas/parsers.py\", line 622, in parse\n",
      "    df = pandas.read_parquet(fname, **kwargs)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 500, in read_parquet\n",
      "    **kwargs,\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 240, in read\n",
      "    path_or_handle, columns=columns, **kwargs\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1942, in read_table\n",
      "    use_pandas_metadata=use_pandas_metadata)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1778, in read\n",
      "    use_threads=use_threads\n",
      "  File \"pyarrow/_dataset.pyx\", line 491, in pyarrow._dataset.Dataset.to_table\n",
      "  File \"pyarrow/_dataset.pyx\", line 3235, in pyarrow._dataset.Scanner.to_table\n",
      "  File \"pyarrow/error.pxi\", line 143, in pyarrow.lib.pyarrow_internal_check_status\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/spec.py\", line 1578, in read\n",
      "    out = self.cache._fetch(self.loc, self.loc + length)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/caching.py\", line 399, in _fetch\n",
      "    out = self.cache[offset : offset + end - start]\n",
      "MemoryError\n",
      "Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::deploy_ray_func()\u001b[39m (pid=24638, ip=172.31.27.60)\n",
      "  File \"/home/emr-notebook/.local/lib/python3.7/site-packages/modin/core/execution/ray/common/task_wrapper.py\", line 40, in deploy_ray_func\n",
      "  File \"/tmp/ray/session_2022-07-06_02-59-12_340846_29218/runtime_resources/pip/11ec394aa27dc2f92256e9847ec87567ef3cace5/virtualenv/lib/python3.7/site-packages/modin/core/storage_formats/pandas/parsers.py\", line 622, in parse\n",
      "    df = pandas.read_parquet(fname, **kwargs)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 500, in read_parquet\n",
      "    **kwargs,\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 240, in read\n",
      "    path_or_handle, columns=columns, **kwargs\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1942, in read_table\n",
      "    use_pandas_metadata=use_pandas_metadata)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1778, in read\n",
      "    use_threads=use_threads\n",
      "  File \"pyarrow/_dataset.pyx\", line 491, in pyarrow._dataset.Dataset.to_table\n",
      "  File \"pyarrow/_dataset.pyx\", line 3235, in pyarrow._dataset.Scanner.to_table\n",
      "  File \"pyarrow/error.pxi\", line 143, in pyarrow.lib.pyarrow_internal_check_status\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/spec.py\", line 1578, in read\n",
      "    out = self.cache._fetch(self.loc, self.loc + length)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/caching.py\", line 399, in _fetch\n",
      "    out = self.cache[offset : offset + end - start]\n",
      "MemoryError\n",
      "Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::deploy_ray_func()\u001b[39m (pid=24638, ip=172.31.27.60)\n",
      "  File \"/home/emr-notebook/.local/lib/python3.7/site-packages/modin/core/execution/ray/common/task_wrapper.py\", line 40, in deploy_ray_func\n",
      "  File \"/tmp/ray/session_2022-07-06_02-59-12_340846_29218/runtime_resources/pip/11ec394aa27dc2f92256e9847ec87567ef3cace5/virtualenv/lib/python3.7/site-packages/modin/core/storage_formats/pandas/parsers.py\", line 622, in parse\n",
      "    df = pandas.read_parquet(fname, **kwargs)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 500, in read_parquet\n",
      "    **kwargs,\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 240, in read\n",
      "    path_or_handle, columns=columns, **kwargs\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1942, in read_table\n",
      "    use_pandas_metadata=use_pandas_metadata)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1778, in read\n",
      "    use_threads=use_threads\n",
      "  File \"pyarrow/_dataset.pyx\", line 491, in pyarrow._dataset.Dataset.to_table\n",
      "  File \"pyarrow/_dataset.pyx\", line 3235, in pyarrow._dataset.Scanner.to_table\n",
      "  File \"pyarrow/error.pxi\", line 143, in pyarrow.lib.pyarrow_internal_check_status\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/spec.py\", line 1578, in read\n",
      "    out = self.cache._fetch(self.loc, self.loc + length)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/caching.py\", line 399, in _fetch\n",
      "    out = self.cache[offset : offset + end - start]\n",
      "MemoryError\n",
      "Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::deploy_ray_func()\u001b[39m (pid=24638, ip=172.31.27.60)\n",
      "  File \"/home/emr-notebook/.local/lib/python3.7/site-packages/modin/core/execution/ray/common/task_wrapper.py\", line 40, in deploy_ray_func\n",
      "  File \"/tmp/ray/session_2022-07-06_02-59-12_340846_29218/runtime_resources/pip/11ec394aa27dc2f92256e9847ec87567ef3cace5/virtualenv/lib/python3.7/site-packages/modin/core/storage_formats/pandas/parsers.py\", line 622, in parse\n",
      "    df = pandas.read_parquet(fname, **kwargs)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 500, in read_parquet\n",
      "    **kwargs,\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 240, in read\n",
      "    path_or_handle, columns=columns, **kwargs\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1942, in read_table\n",
      "    use_pandas_metadata=use_pandas_metadata)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1778, in read\n",
      "    use_threads=use_threads\n",
      "  File \"pyarrow/_dataset.pyx\", line 491, in pyarrow._dataset.Dataset.to_table\n",
      "  File \"pyarrow/_dataset.pyx\", line 3235, in pyarrow._dataset.Scanner.to_table\n",
      "  File \"pyarrow/error.pxi\", line 143, in pyarrow.lib.pyarrow_internal_check_status\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/spec.py\", line 1578, in read\n",
      "    out = self.cache._fetch(self.loc, self.loc + length)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/caching.py\", line 399, in _fetch\n",
      "    out = self.cache[offset : offset + end - start]\n",
      "MemoryError\n",
      "Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::deploy_ray_func()\u001b[39m (pid=24638, ip=172.31.27.60)\n",
      "  File \"/home/emr-notebook/.local/lib/python3.7/site-packages/modin/core/execution/ray/common/task_wrapper.py\", line 40, in deploy_ray_func\n",
      "  File \"/tmp/ray/session_2022-07-06_02-59-12_340846_29218/runtime_resources/pip/11ec394aa27dc2f92256e9847ec87567ef3cace5/virtualenv/lib/python3.7/site-packages/modin/core/storage_formats/pandas/parsers.py\", line 622, in parse\n",
      "    df = pandas.read_parquet(fname, **kwargs)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 500, in read_parquet\n",
      "    **kwargs,\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 240, in read\n",
      "    path_or_handle, columns=columns, **kwargs\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1942, in read_table\n",
      "    use_pandas_metadata=use_pandas_metadata)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1778, in read\n",
      "    use_threads=use_threads\n",
      "  File \"pyarrow/_dataset.pyx\", line 491, in pyarrow._dataset.Dataset.to_table\n",
      "  File \"pyarrow/_dataset.pyx\", line 3235, in pyarrow._dataset.Scanner.to_table\n",
      "  File \"pyarrow/error.pxi\", line 143, in pyarrow.lib.pyarrow_internal_check_status\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/spec.py\", line 1578, in read\n",
      "    out = self.cache._fetch(self.loc, self.loc + length)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/caching.py\", line 399, in _fetch\n",
      "    out = self.cache[offset : offset + end - start]\n",
      "MemoryError\n",
      "Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::deploy_ray_func()\u001b[39m (pid=24638, ip=172.31.27.60)\n",
      "  File \"/home/emr-notebook/.local/lib/python3.7/site-packages/modin/core/execution/ray/common/task_wrapper.py\", line 40, in deploy_ray_func\n",
      "  File \"/tmp/ray/session_2022-07-06_02-59-12_340846_29218/runtime_resources/pip/11ec394aa27dc2f92256e9847ec87567ef3cace5/virtualenv/lib/python3.7/site-packages/modin/core/storage_formats/pandas/parsers.py\", line 622, in parse\n",
      "    df = pandas.read_parquet(fname, **kwargs)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 500, in read_parquet\n",
      "    **kwargs,\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 240, in read\n",
      "    path_or_handle, columns=columns, **kwargs\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1942, in read_table\n",
      "    use_pandas_metadata=use_pandas_metadata)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1778, in read\n",
      "    use_threads=use_threads\n",
      "  File \"pyarrow/_dataset.pyx\", line 491, in pyarrow._dataset.Dataset.to_table\n",
      "  File \"pyarrow/_dataset.pyx\", line 3235, in pyarrow._dataset.Scanner.to_table\n",
      "  File \"pyarrow/error.pxi\", line 143, in pyarrow.lib.pyarrow_internal_check_status\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/spec.py\", line 1578, in read\n",
      "    out = self.cache._fetch(self.loc, self.loc + length)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/caching.py\", line 399, in _fetch\n",
      "    out = self.cache[offset : offset + end - start]\n",
      "MemoryError\n",
      "Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::deploy_ray_func()\u001b[39m (pid=24638, ip=172.31.27.60)\n",
      "  File \"/home/emr-notebook/.local/lib/python3.7/site-packages/modin/core/execution/ray/common/task_wrapper.py\", line 40, in deploy_ray_func\n",
      "  File \"/tmp/ray/session_2022-07-06_02-59-12_340846_29218/runtime_resources/pip/11ec394aa27dc2f92256e9847ec87567ef3cace5/virtualenv/lib/python3.7/site-packages/modin/core/storage_formats/pandas/parsers.py\", line 622, in parse\n",
      "    df = pandas.read_parquet(fname, **kwargs)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 500, in read_parquet\n",
      "    **kwargs,\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 240, in read\n",
      "    path_or_handle, columns=columns, **kwargs\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1942, in read_table\n",
      "    use_pandas_metadata=use_pandas_metadata)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1778, in read\n",
      "    use_threads=use_threads\n",
      "  File \"pyarrow/_dataset.pyx\", line 491, in pyarrow._dataset.Dataset.to_table\n",
      "  File \"pyarrow/_dataset.pyx\", line 3235, in pyarrow._dataset.Scanner.to_table\n",
      "  File \"pyarrow/error.pxi\", line 143, in pyarrow.lib.pyarrow_internal_check_status\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/spec.py\", line 1578, in read\n",
      "    out = self.cache._fetch(self.loc, self.loc + length)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/caching.py\", line 399, in _fetch\n",
      "    out = self.cache[offset : offset + end - start]\n",
      "MemoryError\n",
      "Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::deploy_ray_func()\u001b[39m (pid=24638, ip=172.31.27.60)\n",
      "  File \"/home/emr-notebook/.local/lib/python3.7/site-packages/modin/core/execution/ray/common/task_wrapper.py\", line 40, in deploy_ray_func\n",
      "  File \"/tmp/ray/session_2022-07-06_02-59-12_340846_29218/runtime_resources/pip/11ec394aa27dc2f92256e9847ec87567ef3cace5/virtualenv/lib/python3.7/site-packages/modin/core/storage_formats/pandas/parsers.py\", line 622, in parse\n",
      "    df = pandas.read_parquet(fname, **kwargs)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 500, in read_parquet\n",
      "    **kwargs,\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 240, in read\n",
      "    path_or_handle, columns=columns, **kwargs\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1942, in read_table\n",
      "    use_pandas_metadata=use_pandas_metadata)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1778, in read\n",
      "    use_threads=use_threads\n",
      "  File \"pyarrow/_dataset.pyx\", line 491, in pyarrow._dataset.Dataset.to_table\n",
      "  File \"pyarrow/_dataset.pyx\", line 3235, in pyarrow._dataset.Scanner.to_table\n",
      "  File \"pyarrow/error.pxi\", line 143, in pyarrow.lib.pyarrow_internal_check_status\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/spec.py\", line 1578, in read\n",
      "    out = self.cache._fetch(self.loc, self.loc + length)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/caching.py\", line 399, in _fetch\n",
      "    out = self.cache[offset : offset + end - start]\n",
      "MemoryError\n",
      "Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::deploy_ray_func()\u001b[39m (pid=24638, ip=172.31.27.60)\n",
      "  File \"/home/emr-notebook/.local/lib/python3.7/site-packages/modin/core/execution/ray/common/task_wrapper.py\", line 40, in deploy_ray_func\n",
      "  File \"/tmp/ray/session_2022-07-06_02-59-12_340846_29218/runtime_resources/pip/11ec394aa27dc2f92256e9847ec87567ef3cace5/virtualenv/lib/python3.7/site-packages/modin/core/storage_formats/pandas/parsers.py\", line 622, in parse\n",
      "    df = pandas.read_parquet(fname, **kwargs)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 500, in read_parquet\n",
      "    **kwargs,\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 240, in read\n",
      "    path_or_handle, columns=columns, **kwargs\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1942, in read_table\n",
      "    use_pandas_metadata=use_pandas_metadata)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1778, in read\n",
      "    use_threads=use_threads\n",
      "  File \"pyarrow/_dataset.pyx\", line 491, in pyarrow._dataset.Dataset.to_table\n",
      "  File \"pyarrow/_dataset.pyx\", line 3235, in pyarrow._dataset.Scanner.to_table\n",
      "  File \"pyarrow/error.pxi\", line 143, in pyarrow.lib.pyarrow_internal_check_status\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/spec.py\", line 1578, in read\n",
      "    out = self.cache._fetch(self.loc, self.loc + length)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/caching.py\", line 399, in _fetch\n",
      "    out = self.cache[offset : offset + end - start]\n",
      "MemoryError\n",
      "Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::deploy_ray_func()\u001b[39m (pid=24638, ip=172.31.27.60)\n",
      "  File \"/home/emr-notebook/.local/lib/python3.7/site-packages/modin/core/execution/ray/common/task_wrapper.py\", line 40, in deploy_ray_func\n",
      "  File \"/tmp/ray/session_2022-07-06_02-59-12_340846_29218/runtime_resources/pip/11ec394aa27dc2f92256e9847ec87567ef3cace5/virtualenv/lib/python3.7/site-packages/modin/core/storage_formats/pandas/parsers.py\", line 622, in parse\n",
      "    df = pandas.read_parquet(fname, **kwargs)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 500, in read_parquet\n",
      "    **kwargs,\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 240, in read\n",
      "    path_or_handle, columns=columns, **kwargs\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1942, in read_table\n",
      "    use_pandas_metadata=use_pandas_metadata)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1778, in read\n",
      "    use_threads=use_threads\n",
      "  File \"pyarrow/_dataset.pyx\", line 491, in pyarrow._dataset.Dataset.to_table\n",
      "  File \"pyarrow/_dataset.pyx\", line 3235, in pyarrow._dataset.Scanner.to_table\n",
      "  File \"pyarrow/error.pxi\", line 143, in pyarrow.lib.pyarrow_internal_check_status\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/spec.py\", line 1578, in read\n",
      "    out = self.cache._fetch(self.loc, self.loc + length)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/caching.py\", line 399, in _fetch\n",
      "    out = self.cache[offset : offset + end - start]\n",
      "MemoryError\n",
      "Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::deploy_ray_func()\u001b[39m (pid=24638, ip=172.31.27.60)\n",
      "  File \"/home/emr-notebook/.local/lib/python3.7/site-packages/modin/core/execution/ray/common/task_wrapper.py\", line 40, in deploy_ray_func\n",
      "  File \"/tmp/ray/session_2022-07-06_02-59-12_340846_29218/runtime_resources/pip/11ec394aa27dc2f92256e9847ec87567ef3cace5/virtualenv/lib/python3.7/site-packages/modin/core/storage_formats/pandas/parsers.py\", line 622, in parse\n",
      "    df = pandas.read_parquet(fname, **kwargs)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 500, in read_parquet\n",
      "    **kwargs,\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 240, in read\n",
      "    path_or_handle, columns=columns, **kwargs\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1942, in read_table\n",
      "    use_pandas_metadata=use_pandas_metadata)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1778, in read\n",
      "    use_threads=use_threads\n",
      "  File \"pyarrow/_dataset.pyx\", line 491, in pyarrow._dataset.Dataset.to_table\n",
      "  File \"pyarrow/_dataset.pyx\", line 3235, in pyarrow._dataset.Scanner.to_table\n",
      "  File \"pyarrow/error.pxi\", line 143, in pyarrow.lib.pyarrow_internal_check_status\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/spec.py\", line 1578, in read\n",
      "    out = self.cache._fetch(self.loc, self.loc + length)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/caching.py\", line 399, in _fetch\n",
      "    out = self.cache[offset : offset + end - start]\n",
      "MemoryError\n",
      "Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::deploy_ray_func()\u001b[39m (pid=24638, ip=172.31.27.60)\n",
      "  File \"/home/emr-notebook/.local/lib/python3.7/site-packages/modin/core/execution/ray/common/task_wrapper.py\", line 40, in deploy_ray_func\n",
      "  File \"/tmp/ray/session_2022-07-06_02-59-12_340846_29218/runtime_resources/pip/11ec394aa27dc2f92256e9847ec87567ef3cace5/virtualenv/lib/python3.7/site-packages/modin/core/storage_formats/pandas/parsers.py\", line 622, in parse\n",
      "    df = pandas.read_parquet(fname, **kwargs)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 500, in read_parquet\n",
      "    **kwargs,\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 240, in read\n",
      "    path_or_handle, columns=columns, **kwargs\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1942, in read_table\n",
      "    use_pandas_metadata=use_pandas_metadata)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1778, in read\n",
      "    use_threads=use_threads\n",
      "  File \"pyarrow/_dataset.pyx\", line 491, in pyarrow._dataset.Dataset.to_table\n",
      "  File \"pyarrow/_dataset.pyx\", line 3235, in pyarrow._dataset.Scanner.to_table\n",
      "  File \"pyarrow/error.pxi\", line 143, in pyarrow.lib.pyarrow_internal_check_status\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/spec.py\", line 1578, in read\n",
      "    out = self.cache._fetch(self.loc, self.loc + length)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/caching.py\", line 399, in _fetch\n",
      "    out = self.cache[offset : offset + end - start]\n",
      "MemoryError\n",
      "Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::deploy_ray_func()\u001b[39m (pid=24638, ip=172.31.27.60)\n",
      "  File \"/home/emr-notebook/.local/lib/python3.7/site-packages/modin/core/execution/ray/common/task_wrapper.py\", line 40, in deploy_ray_func\n",
      "  File \"/tmp/ray/session_2022-07-06_02-59-12_340846_29218/runtime_resources/pip/11ec394aa27dc2f92256e9847ec87567ef3cace5/virtualenv/lib/python3.7/site-packages/modin/core/storage_formats/pandas/parsers.py\", line 622, in parse\n",
      "    df = pandas.read_parquet(fname, **kwargs)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 500, in read_parquet\n",
      "    **kwargs,\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 240, in read\n",
      "    path_or_handle, columns=columns, **kwargs\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1942, in read_table\n",
      "    use_pandas_metadata=use_pandas_metadata)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1778, in read\n",
      "    use_threads=use_threads\n",
      "  File \"pyarrow/_dataset.pyx\", line 491, in pyarrow._dataset.Dataset.to_table\n",
      "  File \"pyarrow/_dataset.pyx\", line 3235, in pyarrow._dataset.Scanner.to_table\n",
      "  File \"pyarrow/error.pxi\", line 143, in pyarrow.lib.pyarrow_internal_check_status\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/spec.py\", line 1578, in read\n",
      "    out = self.cache._fetch(self.loc, self.loc + length)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/caching.py\", line 399, in _fetch\n",
      "    out = self.cache[offset : offset + end - start]\n",
      "MemoryError\n",
      "Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::deploy_ray_func()\u001b[39m (pid=24638, ip=172.31.27.60)\n",
      "  File \"/home/emr-notebook/.local/lib/python3.7/site-packages/modin/core/execution/ray/common/task_wrapper.py\", line 40, in deploy_ray_func\n",
      "  File \"/tmp/ray/session_2022-07-06_02-59-12_340846_29218/runtime_resources/pip/11ec394aa27dc2f92256e9847ec87567ef3cace5/virtualenv/lib/python3.7/site-packages/modin/core/storage_formats/pandas/parsers.py\", line 622, in parse\n",
      "    df = pandas.read_parquet(fname, **kwargs)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 500, in read_parquet\n",
      "    **kwargs,\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 240, in read\n",
      "    path_or_handle, columns=columns, **kwargs\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1942, in read_table\n",
      "    use_pandas_metadata=use_pandas_metadata)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1778, in read\n",
      "    use_threads=use_threads\n",
      "  File \"pyarrow/_dataset.pyx\", line 491, in pyarrow._dataset.Dataset.to_table\n",
      "  File \"pyarrow/_dataset.pyx\", line 3235, in pyarrow._dataset.Scanner.to_table\n",
      "  File \"pyarrow/error.pxi\", line 143, in pyarrow.lib.pyarrow_internal_check_status\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/spec.py\", line 1578, in read\n",
      "    out = self.cache._fetch(self.loc, self.loc + length)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/caching.py\", line 399, in _fetch\n",
      "    out = self.cache[offset : offset + end - start]\n",
      "MemoryError\n",
      "Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::deploy_ray_func()\u001b[39m (pid=24638, ip=172.31.27.60)\n",
      "  File \"/home/emr-notebook/.local/lib/python3.7/site-packages/modin/core/execution/ray/common/task_wrapper.py\", line 40, in deploy_ray_func\n",
      "  File \"/tmp/ray/session_2022-07-06_02-59-12_340846_29218/runtime_resources/pip/11ec394aa27dc2f92256e9847ec87567ef3cace5/virtualenv/lib/python3.7/site-packages/modin/core/storage_formats/pandas/parsers.py\", line 622, in parse\n",
      "    df = pandas.read_parquet(fname, **kwargs)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 500, in read_parquet\n",
      "    **kwargs,\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 240, in read\n",
      "    path_or_handle, columns=columns, **kwargs\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1942, in read_table\n",
      "    use_pandas_metadata=use_pandas_metadata)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1778, in read\n",
      "    use_threads=use_threads\n",
      "  File \"pyarrow/_dataset.pyx\", line 491, in pyarrow._dataset.Dataset.to_table\n",
      "  File \"pyarrow/_dataset.pyx\", line 3235, in pyarrow._dataset.Scanner.to_table\n",
      "  File \"pyarrow/error.pxi\", line 143, in pyarrow.lib.pyarrow_internal_check_status\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/spec.py\", line 1578, in read\n",
      "    out = self.cache._fetch(self.loc, self.loc + length)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/caching.py\", line 399, in _fetch\n",
      "    out = self.cache[offset : offset + end - start]\n",
      "MemoryError\n",
      "Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::deploy_ray_func()\u001b[39m (pid=24638, ip=172.31.27.60)\n",
      "  File \"/home/emr-notebook/.local/lib/python3.7/site-packages/modin/core/execution/ray/common/task_wrapper.py\", line 40, in deploy_ray_func\n",
      "  File \"/tmp/ray/session_2022-07-06_02-59-12_340846_29218/runtime_resources/pip/11ec394aa27dc2f92256e9847ec87567ef3cace5/virtualenv/lib/python3.7/site-packages/modin/core/storage_formats/pandas/parsers.py\", line 622, in parse\n",
      "    df = pandas.read_parquet(fname, **kwargs)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 500, in read_parquet\n",
      "    **kwargs,\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 240, in read\n",
      "    path_or_handle, columns=columns, **kwargs\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1942, in read_table\n",
      "    use_pandas_metadata=use_pandas_metadata)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1778, in read\n",
      "    use_threads=use_threads\n",
      "  File \"pyarrow/_dataset.pyx\", line 491, in pyarrow._dataset.Dataset.to_table\n",
      "  File \"pyarrow/_dataset.pyx\", line 3235, in pyarrow._dataset.Scanner.to_table\n",
      "  File \"pyarrow/error.pxi\", line 143, in pyarrow.lib.pyarrow_internal_check_status\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/spec.py\", line 1578, in read\n",
      "    out = self.cache._fetch(self.loc, self.loc + length)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/caching.py\", line 399, in _fetch\n",
      "    out = self.cache[offset : offset + end - start]\n",
      "MemoryError\n",
      "Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::deploy_ray_func()\u001b[39m (pid=24638, ip=172.31.27.60)\n",
      "  File \"/home/emr-notebook/.local/lib/python3.7/site-packages/modin/core/execution/ray/common/task_wrapper.py\", line 40, in deploy_ray_func\n",
      "  File \"/tmp/ray/session_2022-07-06_02-59-12_340846_29218/runtime_resources/pip/11ec394aa27dc2f92256e9847ec87567ef3cace5/virtualenv/lib/python3.7/site-packages/modin/core/storage_formats/pandas/parsers.py\", line 622, in parse\n",
      "    df = pandas.read_parquet(fname, **kwargs)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 500, in read_parquet\n",
      "    **kwargs,\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 240, in read\n",
      "    path_or_handle, columns=columns, **kwargs\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1942, in read_table\n",
      "    use_pandas_metadata=use_pandas_metadata)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1778, in read\n",
      "    use_threads=use_threads\n",
      "  File \"pyarrow/_dataset.pyx\", line 491, in pyarrow._dataset.Dataset.to_table\n",
      "  File \"pyarrow/_dataset.pyx\", line 3235, in pyarrow._dataset.Scanner.to_table\n",
      "  File \"pyarrow/error.pxi\", line 143, in pyarrow.lib.pyarrow_internal_check_status\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/spec.py\", line 1578, in read\n",
      "    out = self.cache._fetch(self.loc, self.loc + length)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/caching.py\", line 399, in _fetch\n",
      "    out = self.cache[offset : offset + end - start]\n",
      "MemoryError\n",
      "Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::deploy_ray_func()\u001b[39m (pid=24638, ip=172.31.27.60)\n",
      "  File \"/home/emr-notebook/.local/lib/python3.7/site-packages/modin/core/execution/ray/common/task_wrapper.py\", line 40, in deploy_ray_func\n",
      "  File \"/tmp/ray/session_2022-07-06_02-59-12_340846_29218/runtime_resources/pip/11ec394aa27dc2f92256e9847ec87567ef3cace5/virtualenv/lib/python3.7/site-packages/modin/core/storage_formats/pandas/parsers.py\", line 622, in parse\n",
      "    df = pandas.read_parquet(fname, **kwargs)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 500, in read_parquet\n",
      "    **kwargs,\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 240, in read\n",
      "    path_or_handle, columns=columns, **kwargs\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1942, in read_table\n",
      "    use_pandas_metadata=use_pandas_metadata)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1778, in read\n",
      "    use_threads=use_threads\n",
      "  File \"pyarrow/_dataset.pyx\", line 491, in pyarrow._dataset.Dataset.to_table\n",
      "  File \"pyarrow/_dataset.pyx\", line 3235, in pyarrow._dataset.Scanner.to_table\n",
      "  File \"pyarrow/error.pxi\", line 143, in pyarrow.lib.pyarrow_internal_check_status\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/spec.py\", line 1578, in read\n",
      "    out = self.cache._fetch(self.loc, self.loc + length)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/caching.py\", line 399, in _fetch\n",
      "    out = self.cache[offset : offset + end - start]\n",
      "MemoryError\n",
      "Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::deploy_ray_func()\u001b[39m (pid=24638, ip=172.31.27.60)\n",
      "  File \"/home/emr-notebook/.local/lib/python3.7/site-packages/modin/core/execution/ray/common/task_wrapper.py\", line 40, in deploy_ray_func\n",
      "  File \"/tmp/ray/session_2022-07-06_02-59-12_340846_29218/runtime_resources/pip/11ec394aa27dc2f92256e9847ec87567ef3cace5/virtualenv/lib/python3.7/site-packages/modin/core/storage_formats/pandas/parsers.py\", line 622, in parse\n",
      "    df = pandas.read_parquet(fname, **kwargs)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 500, in read_parquet\n",
      "    **kwargs,\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 240, in read\n",
      "    path_or_handle, columns=columns, **kwargs\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1942, in read_table\n",
      "    use_pandas_metadata=use_pandas_metadata)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1778, in read\n",
      "    use_threads=use_threads\n",
      "  File \"pyarrow/_dataset.pyx\", line 491, in pyarrow._dataset.Dataset.to_table\n",
      "  File \"pyarrow/_dataset.pyx\", line 3235, in pyarrow._dataset.Scanner.to_table\n",
      "  File \"pyarrow/error.pxi\", line 143, in pyarrow.lib.pyarrow_internal_check_status\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/spec.py\", line 1578, in read\n",
      "    out = self.cache._fetch(self.loc, self.loc + length)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/caching.py\", line 399, in _fetch\n",
      "    out = self.cache[offset : offset + end - start]\n",
      "MemoryError\n",
      "Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::deploy_ray_func()\u001b[39m (pid=24638, ip=172.31.27.60)\n",
      "  File \"/home/emr-notebook/.local/lib/python3.7/site-packages/modin/core/execution/ray/common/task_wrapper.py\", line 40, in deploy_ray_func\n",
      "  File \"/tmp/ray/session_2022-07-06_02-59-12_340846_29218/runtime_resources/pip/11ec394aa27dc2f92256e9847ec87567ef3cace5/virtualenv/lib/python3.7/site-packages/modin/core/storage_formats/pandas/parsers.py\", line 622, in parse\n",
      "    df = pandas.read_parquet(fname, **kwargs)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 500, in read_parquet\n",
      "    **kwargs,\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 240, in read\n",
      "    path_or_handle, columns=columns, **kwargs\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1942, in read_table\n",
      "    use_pandas_metadata=use_pandas_metadata)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1778, in read\n",
      "    use_threads=use_threads\n",
      "  File \"pyarrow/_dataset.pyx\", line 491, in pyarrow._dataset.Dataset.to_table\n",
      "  File \"pyarrow/_dataset.pyx\", line 3235, in pyarrow._dataset.Scanner.to_table\n",
      "  File \"pyarrow/error.pxi\", line 143, in pyarrow.lib.pyarrow_internal_check_status\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/spec.py\", line 1578, in read\n",
      "    out = self.cache._fetch(self.loc, self.loc + length)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/caching.py\", line 399, in _fetch\n",
      "    out = self.cache[offset : offset + end - start]\n",
      "MemoryError\n",
      "Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::deploy_ray_func()\u001b[39m (pid=24638, ip=172.31.27.60)\n",
      "  File \"/home/emr-notebook/.local/lib/python3.7/site-packages/modin/core/execution/ray/common/task_wrapper.py\", line 40, in deploy_ray_func\n",
      "  File \"/tmp/ray/session_2022-07-06_02-59-12_340846_29218/runtime_resources/pip/11ec394aa27dc2f92256e9847ec87567ef3cace5/virtualenv/lib/python3.7/site-packages/modin/core/storage_formats/pandas/parsers.py\", line 622, in parse\n",
      "    df = pandas.read_parquet(fname, **kwargs)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 500, in read_parquet\n",
      "    **kwargs,\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 240, in read\n",
      "    path_or_handle, columns=columns, **kwargs\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1942, in read_table\n",
      "    use_pandas_metadata=use_pandas_metadata)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1778, in read\n",
      "    use_threads=use_threads\n",
      "  File \"pyarrow/_dataset.pyx\", line 491, in pyarrow._dataset.Dataset.to_table\n",
      "  File \"pyarrow/_dataset.pyx\", line 3235, in pyarrow._dataset.Scanner.to_table\n",
      "  File \"pyarrow/error.pxi\", line 143, in pyarrow.lib.pyarrow_internal_check_status\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/spec.py\", line 1578, in read\n",
      "    out = self.cache._fetch(self.loc, self.loc + length)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/caching.py\", line 399, in _fetch\n",
      "    out = self.cache[offset : offset + end - start]\n",
      "MemoryError\n",
      "Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::deploy_ray_func()\u001b[39m (pid=24638, ip=172.31.27.60)\n",
      "  File \"/home/emr-notebook/.local/lib/python3.7/site-packages/modin/core/execution/ray/common/task_wrapper.py\", line 40, in deploy_ray_func\n",
      "  File \"/tmp/ray/session_2022-07-06_02-59-12_340846_29218/runtime_resources/pip/11ec394aa27dc2f92256e9847ec87567ef3cace5/virtualenv/lib/python3.7/site-packages/modin/core/storage_formats/pandas/parsers.py\", line 622, in parse\n",
      "    df = pandas.read_parquet(fname, **kwargs)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 500, in read_parquet\n",
      "    **kwargs,\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 240, in read\n",
      "    path_or_handle, columns=columns, **kwargs\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1942, in read_table\n",
      "    use_pandas_metadata=use_pandas_metadata)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1778, in read\n",
      "    use_threads=use_threads\n",
      "  File \"pyarrow/_dataset.pyx\", line 491, in pyarrow._dataset.Dataset.to_table\n",
      "  File \"pyarrow/_dataset.pyx\", line 3235, in pyarrow._dataset.Scanner.to_table\n",
      "  File \"pyarrow/error.pxi\", line 143, in pyarrow.lib.pyarrow_internal_check_status\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/spec.py\", line 1578, in read\n",
      "    out = self.cache._fetch(self.loc, self.loc + length)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/caching.py\", line 399, in _fetch\n",
      "    out = self.cache[offset : offset + end - start]\n",
      "MemoryError\n",
      "Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::deploy_ray_func()\u001b[39m (pid=24638, ip=172.31.27.60)\n",
      "  File \"/home/emr-notebook/.local/lib/python3.7/site-packages/modin/core/execution/ray/common/task_wrapper.py\", line 40, in deploy_ray_func\n",
      "  File \"/tmp/ray/session_2022-07-06_02-59-12_340846_29218/runtime_resources/pip/11ec394aa27dc2f92256e9847ec87567ef3cace5/virtualenv/lib/python3.7/site-packages/modin/core/storage_formats/pandas/parsers.py\", line 622, in parse\n",
      "    df = pandas.read_parquet(fname, **kwargs)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 500, in read_parquet\n",
      "    **kwargs,\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 240, in read\n",
      "    path_or_handle, columns=columns, **kwargs\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1942, in read_table\n",
      "    use_pandas_metadata=use_pandas_metadata)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1778, in read\n",
      "    use_threads=use_threads\n",
      "  File \"pyarrow/_dataset.pyx\", line 491, in pyarrow._dataset.Dataset.to_table\n",
      "  File \"pyarrow/_dataset.pyx\", line 3235, in pyarrow._dataset.Scanner.to_table\n",
      "  File \"pyarrow/error.pxi\", line 143, in pyarrow.lib.pyarrow_internal_check_status\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/spec.py\", line 1578, in read\n",
      "    out = self.cache._fetch(self.loc, self.loc + length)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/caching.py\", line 399, in _fetch\n",
      "    out = self.cache[offset : offset + end - start]\n",
      "MemoryError\n",
      "Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::deploy_ray_func()\u001b[39m (pid=24638, ip=172.31.27.60)\n",
      "  File \"/home/emr-notebook/.local/lib/python3.7/site-packages/modin/core/execution/ray/common/task_wrapper.py\", line 40, in deploy_ray_func\n",
      "  File \"/tmp/ray/session_2022-07-06_02-59-12_340846_29218/runtime_resources/pip/11ec394aa27dc2f92256e9847ec87567ef3cace5/virtualenv/lib/python3.7/site-packages/modin/core/storage_formats/pandas/parsers.py\", line 622, in parse\n",
      "    df = pandas.read_parquet(fname, **kwargs)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 500, in read_parquet\n",
      "    **kwargs,\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 240, in read\n",
      "    path_or_handle, columns=columns, **kwargs\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1942, in read_table\n",
      "    use_pandas_metadata=use_pandas_metadata)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1778, in read\n",
      "    use_threads=use_threads\n",
      "  File \"pyarrow/_dataset.pyx\", line 491, in pyarrow._dataset.Dataset.to_table\n",
      "  File \"pyarrow/_dataset.pyx\", line 3235, in pyarrow._dataset.Scanner.to_table\n",
      "  File \"pyarrow/error.pxi\", line 143, in pyarrow.lib.pyarrow_internal_check_status\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/spec.py\", line 1578, in read\n",
      "    out = self.cache._fetch(self.loc, self.loc + length)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/caching.py\", line 399, in _fetch\n",
      "    out = self.cache[offset : offset + end - start]\n",
      "MemoryError\n",
      "Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::deploy_ray_func()\u001b[39m (pid=24638, ip=172.31.27.60)\n",
      "  File \"/home/emr-notebook/.local/lib/python3.7/site-packages/modin/core/execution/ray/common/task_wrapper.py\", line 40, in deploy_ray_func\n",
      "  File \"/tmp/ray/session_2022-07-06_02-59-12_340846_29218/runtime_resources/pip/11ec394aa27dc2f92256e9847ec87567ef3cace5/virtualenv/lib/python3.7/site-packages/modin/core/storage_formats/pandas/parsers.py\", line 622, in parse\n",
      "    df = pandas.read_parquet(fname, **kwargs)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 500, in read_parquet\n",
      "    **kwargs,\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 240, in read\n",
      "    path_or_handle, columns=columns, **kwargs\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1942, in read_table\n",
      "    use_pandas_metadata=use_pandas_metadata)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1778, in read\n",
      "    use_threads=use_threads\n",
      "  File \"pyarrow/_dataset.pyx\", line 491, in pyarrow._dataset.Dataset.to_table\n",
      "  File \"pyarrow/_dataset.pyx\", line 3235, in pyarrow._dataset.Scanner.to_table\n",
      "  File \"pyarrow/error.pxi\", line 143, in pyarrow.lib.pyarrow_internal_check_status\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/spec.py\", line 1578, in read\n",
      "    out = self.cache._fetch(self.loc, self.loc + length)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/caching.py\", line 399, in _fetch\n",
      "    out = self.cache[offset : offset + end - start]\n",
      "MemoryError\n",
      "Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::deploy_ray_func()\u001b[39m (pid=24638, ip=172.31.27.60)\n",
      "  File \"/home/emr-notebook/.local/lib/python3.7/site-packages/modin/core/execution/ray/common/task_wrapper.py\", line 40, in deploy_ray_func\n",
      "  File \"/tmp/ray/session_2022-07-06_02-59-12_340846_29218/runtime_resources/pip/11ec394aa27dc2f92256e9847ec87567ef3cace5/virtualenv/lib/python3.7/site-packages/modin/core/storage_formats/pandas/parsers.py\", line 622, in parse\n",
      "    df = pandas.read_parquet(fname, **kwargs)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 500, in read_parquet\n",
      "    **kwargs,\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 240, in read\n",
      "    path_or_handle, columns=columns, **kwargs\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1942, in read_table\n",
      "    use_pandas_metadata=use_pandas_metadata)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1778, in read\n",
      "    use_threads=use_threads\n",
      "  File \"pyarrow/_dataset.pyx\", line 491, in pyarrow._dataset.Dataset.to_table\n",
      "  File \"pyarrow/_dataset.pyx\", line 3235, in pyarrow._dataset.Scanner.to_table\n",
      "  File \"pyarrow/error.pxi\", line 143, in pyarrow.lib.pyarrow_internal_check_status\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/spec.py\", line 1578, in read\n",
      "    out = self.cache._fetch(self.loc, self.loc + length)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/caching.py\", line 399, in _fetch\n",
      "    out = self.cache[offset : offset + end - start]\n",
      "MemoryError\n",
      "Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::deploy_ray_func()\u001b[39m (pid=24638, ip=172.31.27.60)\n",
      "  File \"/home/emr-notebook/.local/lib/python3.7/site-packages/modin/core/execution/ray/common/task_wrapper.py\", line 40, in deploy_ray_func\n",
      "  File \"/tmp/ray/session_2022-07-06_02-59-12_340846_29218/runtime_resources/pip/11ec394aa27dc2f92256e9847ec87567ef3cace5/virtualenv/lib/python3.7/site-packages/modin/core/storage_formats/pandas/parsers.py\", line 622, in parse\n",
      "    df = pandas.read_parquet(fname, **kwargs)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 500, in read_parquet\n",
      "    **kwargs,\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 240, in read\n",
      "    path_or_handle, columns=columns, **kwargs\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1942, in read_table\n",
      "    use_pandas_metadata=use_pandas_metadata)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1778, in read\n",
      "    use_threads=use_threads\n",
      "  File \"pyarrow/_dataset.pyx\", line 491, in pyarrow._dataset.Dataset.to_table\n",
      "  File \"pyarrow/_dataset.pyx\", line 3235, in pyarrow._dataset.Scanner.to_table\n",
      "  File \"pyarrow/error.pxi\", line 143, in pyarrow.lib.pyarrow_internal_check_status\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/spec.py\", line 1578, in read\n",
      "    out = self.cache._fetch(self.loc, self.loc + length)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/caching.py\", line 399, in _fetch\n",
      "    out = self.cache[offset : offset + end - start]\n",
      "MemoryError\n",
      "Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::deploy_ray_func()\u001b[39m (pid=24638, ip=172.31.27.60)\n",
      "  File \"/home/emr-notebook/.local/lib/python3.7/site-packages/modin/core/execution/ray/common/task_wrapper.py\", line 40, in deploy_ray_func\n",
      "  File \"/tmp/ray/session_2022-07-06_02-59-12_340846_29218/runtime_resources/pip/11ec394aa27dc2f92256e9847ec87567ef3cace5/virtualenv/lib/python3.7/site-packages/modin/core/storage_formats/pandas/parsers.py\", line 622, in parse\n",
      "    df = pandas.read_parquet(fname, **kwargs)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 500, in read_parquet\n",
      "    **kwargs,\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 240, in read\n",
      "    path_or_handle, columns=columns, **kwargs\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1942, in read_table\n",
      "    use_pandas_metadata=use_pandas_metadata)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1778, in read\n",
      "    use_threads=use_threads\n",
      "  File \"pyarrow/_dataset.pyx\", line 491, in pyarrow._dataset.Dataset.to_table\n",
      "  File \"pyarrow/_dataset.pyx\", line 3235, in pyarrow._dataset.Scanner.to_table\n",
      "  File \"pyarrow/error.pxi\", line 143, in pyarrow.lib.pyarrow_internal_check_status\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/spec.py\", line 1578, in read\n",
      "    out = self.cache._fetch(self.loc, self.loc + length)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/caching.py\", line 399, in _fetch\n",
      "    out = self.cache[offset : offset + end - start]\n",
      "MemoryError\n",
      "Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::deploy_ray_func()\u001b[39m (pid=24638, ip=172.31.27.60)\n",
      "  File \"/home/emr-notebook/.local/lib/python3.7/site-packages/modin/core/execution/ray/common/task_wrapper.py\", line 40, in deploy_ray_func\n",
      "  File \"/tmp/ray/session_2022-07-06_02-59-12_340846_29218/runtime_resources/pip/11ec394aa27dc2f92256e9847ec87567ef3cace5/virtualenv/lib/python3.7/site-packages/modin/core/storage_formats/pandas/parsers.py\", line 622, in parse\n",
      "    df = pandas.read_parquet(fname, **kwargs)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 500, in read_parquet\n",
      "    **kwargs,\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 240, in read\n",
      "    path_or_handle, columns=columns, **kwargs\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1942, in read_table\n",
      "    use_pandas_metadata=use_pandas_metadata)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1778, in read\n",
      "    use_threads=use_threads\n",
      "  File \"pyarrow/_dataset.pyx\", line 491, in pyarrow._dataset.Dataset.to_table\n",
      "  File \"pyarrow/_dataset.pyx\", line 3235, in pyarrow._dataset.Scanner.to_table\n",
      "  File \"pyarrow/error.pxi\", line 143, in pyarrow.lib.pyarrow_internal_check_status\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/spec.py\", line 1578, in read\n",
      "    out = self.cache._fetch(self.loc, self.loc + length)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/caching.py\", line 399, in _fetch\n",
      "    out = self.cache[offset : offset + end - start]\n",
      "MemoryError\n",
      "Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::deploy_ray_func()\u001b[39m (pid=24638, ip=172.31.27.60)\n",
      "  File \"/home/emr-notebook/.local/lib/python3.7/site-packages/modin/core/execution/ray/common/task_wrapper.py\", line 40, in deploy_ray_func\n",
      "  File \"/tmp/ray/session_2022-07-06_02-59-12_340846_29218/runtime_resources/pip/11ec394aa27dc2f92256e9847ec87567ef3cace5/virtualenv/lib/python3.7/site-packages/modin/core/storage_formats/pandas/parsers.py\", line 622, in parse\n",
      "    df = pandas.read_parquet(fname, **kwargs)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 500, in read_parquet\n",
      "    **kwargs,\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 240, in read\n",
      "    path_or_handle, columns=columns, **kwargs\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1942, in read_table\n",
      "    use_pandas_metadata=use_pandas_metadata)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1778, in read\n",
      "    use_threads=use_threads\n",
      "  File \"pyarrow/_dataset.pyx\", line 491, in pyarrow._dataset.Dataset.to_table\n",
      "  File \"pyarrow/_dataset.pyx\", line 3235, in pyarrow._dataset.Scanner.to_table\n",
      "  File \"pyarrow/error.pxi\", line 143, in pyarrow.lib.pyarrow_internal_check_status\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/spec.py\", line 1578, in read\n",
      "    out = self.cache._fetch(self.loc, self.loc + length)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/caching.py\", line 399, in _fetch\n",
      "    out = self.cache[offset : offset + end - start]\n",
      "MemoryError\n",
      "Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::deploy_ray_func()\u001b[39m (pid=24638, ip=172.31.27.60)\n",
      "  File \"/home/emr-notebook/.local/lib/python3.7/site-packages/modin/core/execution/ray/common/task_wrapper.py\", line 40, in deploy_ray_func\n",
      "  File \"/tmp/ray/session_2022-07-06_02-59-12_340846_29218/runtime_resources/pip/11ec394aa27dc2f92256e9847ec87567ef3cace5/virtualenv/lib/python3.7/site-packages/modin/core/storage_formats/pandas/parsers.py\", line 622, in parse\n",
      "    df = pandas.read_parquet(fname, **kwargs)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 500, in read_parquet\n",
      "    **kwargs,\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 240, in read\n",
      "    path_or_handle, columns=columns, **kwargs\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1942, in read_table\n",
      "    use_pandas_metadata=use_pandas_metadata)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1778, in read\n",
      "    use_threads=use_threads\n",
      "  File \"pyarrow/_dataset.pyx\", line 491, in pyarrow._dataset.Dataset.to_table\n",
      "  File \"pyarrow/_dataset.pyx\", line 3235, in pyarrow._dataset.Scanner.to_table\n",
      "  File \"pyarrow/error.pxi\", line 143, in pyarrow.lib.pyarrow_internal_check_status\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/spec.py\", line 1578, in read\n",
      "    out = self.cache._fetch(self.loc, self.loc + length)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/caching.py\", line 399, in _fetch\n",
      "    out = self.cache[offset : offset + end - start]\n",
      "MemoryError\n",
      "Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::deploy_ray_func()\u001b[39m (pid=24638, ip=172.31.27.60)\n",
      "  File \"/home/emr-notebook/.local/lib/python3.7/site-packages/modin/core/execution/ray/common/task_wrapper.py\", line 40, in deploy_ray_func\n",
      "  File \"/tmp/ray/session_2022-07-06_02-59-12_340846_29218/runtime_resources/pip/11ec394aa27dc2f92256e9847ec87567ef3cace5/virtualenv/lib/python3.7/site-packages/modin/core/storage_formats/pandas/parsers.py\", line 622, in parse\n",
      "    df = pandas.read_parquet(fname, **kwargs)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 500, in read_parquet\n",
      "    **kwargs,\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 240, in read\n",
      "    path_or_handle, columns=columns, **kwargs\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1942, in read_table\n",
      "    use_pandas_metadata=use_pandas_metadata)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1778, in read\n",
      "    use_threads=use_threads\n",
      "  File \"pyarrow/_dataset.pyx\", line 491, in pyarrow._dataset.Dataset.to_table\n",
      "  File \"pyarrow/_dataset.pyx\", line 3235, in pyarrow._dataset.Scanner.to_table\n",
      "  File \"pyarrow/error.pxi\", line 143, in pyarrow.lib.pyarrow_internal_check_status\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/spec.py\", line 1578, in read\n",
      "    out = self.cache._fetch(self.loc, self.loc + length)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/caching.py\", line 399, in _fetch\n",
      "    out = self.cache[offset : offset + end - start]\n",
      "MemoryError\n",
      "Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::deploy_ray_func()\u001b[39m (pid=24638, ip=172.31.27.60)\n",
      "  File \"/home/emr-notebook/.local/lib/python3.7/site-packages/modin/core/execution/ray/common/task_wrapper.py\", line 40, in deploy_ray_func\n",
      "  File \"/tmp/ray/session_2022-07-06_02-59-12_340846_29218/runtime_resources/pip/11ec394aa27dc2f92256e9847ec87567ef3cace5/virtualenv/lib/python3.7/site-packages/modin/core/storage_formats/pandas/parsers.py\", line 622, in parse\n",
      "    df = pandas.read_parquet(fname, **kwargs)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 500, in read_parquet\n",
      "    **kwargs,\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 240, in read\n",
      "    path_or_handle, columns=columns, **kwargs\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1942, in read_table\n",
      "    use_pandas_metadata=use_pandas_metadata)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1778, in read\n",
      "    use_threads=use_threads\n",
      "  File \"pyarrow/_dataset.pyx\", line 491, in pyarrow._dataset.Dataset.to_table\n",
      "  File \"pyarrow/_dataset.pyx\", line 3235, in pyarrow._dataset.Scanner.to_table\n",
      "  File \"pyarrow/error.pxi\", line 143, in pyarrow.lib.pyarrow_internal_check_status\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/spec.py\", line 1578, in read\n",
      "    out = self.cache._fetch(self.loc, self.loc + length)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/caching.py\", line 399, in _fetch\n",
      "    out = self.cache[offset : offset + end - start]\n",
      "MemoryError\n",
      "Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::deploy_ray_func()\u001b[39m (pid=24638, ip=172.31.27.60)\n",
      "  File \"/home/emr-notebook/.local/lib/python3.7/site-packages/modin/core/execution/ray/common/task_wrapper.py\", line 40, in deploy_ray_func\n",
      "  File \"/tmp/ray/session_2022-07-06_02-59-12_340846_29218/runtime_resources/pip/11ec394aa27dc2f92256e9847ec87567ef3cace5/virtualenv/lib/python3.7/site-packages/modin/core/storage_formats/pandas/parsers.py\", line 622, in parse\n",
      "    df = pandas.read_parquet(fname, **kwargs)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 500, in read_parquet\n",
      "    **kwargs,\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 240, in read\n",
      "    path_or_handle, columns=columns, **kwargs\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1942, in read_table\n",
      "    use_pandas_metadata=use_pandas_metadata)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1778, in read\n",
      "    use_threads=use_threads\n",
      "  File \"pyarrow/_dataset.pyx\", line 491, in pyarrow._dataset.Dataset.to_table\n",
      "  File \"pyarrow/_dataset.pyx\", line 3235, in pyarrow._dataset.Scanner.to_table\n",
      "  File \"pyarrow/error.pxi\", line 143, in pyarrow.lib.pyarrow_internal_check_status\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/spec.py\", line 1578, in read\n",
      "    out = self.cache._fetch(self.loc, self.loc + length)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/caching.py\", line 399, in _fetch\n",
      "    out = self.cache[offset : offset + end - start]\n",
      "MemoryError\n",
      "Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::deploy_ray_func()\u001b[39m (pid=24638, ip=172.31.27.60)\n",
      "  File \"/home/emr-notebook/.local/lib/python3.7/site-packages/modin/core/execution/ray/common/task_wrapper.py\", line 40, in deploy_ray_func\n",
      "  File \"/tmp/ray/session_2022-07-06_02-59-12_340846_29218/runtime_resources/pip/11ec394aa27dc2f92256e9847ec87567ef3cace5/virtualenv/lib/python3.7/site-packages/modin/core/storage_formats/pandas/parsers.py\", line 622, in parse\n",
      "    df = pandas.read_parquet(fname, **kwargs)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 500, in read_parquet\n",
      "    **kwargs,\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 240, in read\n",
      "    path_or_handle, columns=columns, **kwargs\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1942, in read_table\n",
      "    use_pandas_metadata=use_pandas_metadata)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1778, in read\n",
      "    use_threads=use_threads\n",
      "  File \"pyarrow/_dataset.pyx\", line 491, in pyarrow._dataset.Dataset.to_table\n",
      "  File \"pyarrow/_dataset.pyx\", line 3235, in pyarrow._dataset.Scanner.to_table\n",
      "  File \"pyarrow/error.pxi\", line 143, in pyarrow.lib.pyarrow_internal_check_status\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/spec.py\", line 1578, in read\n",
      "    out = self.cache._fetch(self.loc, self.loc + length)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/caching.py\", line 399, in _fetch\n",
      "    out = self.cache[offset : offset + end - start]\n",
      "MemoryError\n",
      "Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::deploy_ray_func()\u001b[39m (pid=24638, ip=172.31.27.60)\n",
      "  File \"/home/emr-notebook/.local/lib/python3.7/site-packages/modin/core/execution/ray/common/task_wrapper.py\", line 40, in deploy_ray_func\n",
      "  File \"/tmp/ray/session_2022-07-06_02-59-12_340846_29218/runtime_resources/pip/11ec394aa27dc2f92256e9847ec87567ef3cace5/virtualenv/lib/python3.7/site-packages/modin/core/storage_formats/pandas/parsers.py\", line 622, in parse\n",
      "    df = pandas.read_parquet(fname, **kwargs)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 500, in read_parquet\n",
      "    **kwargs,\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 240, in read\n",
      "    path_or_handle, columns=columns, **kwargs\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1942, in read_table\n",
      "    use_pandas_metadata=use_pandas_metadata)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1778, in read\n",
      "    use_threads=use_threads\n",
      "  File \"pyarrow/_dataset.pyx\", line 491, in pyarrow._dataset.Dataset.to_table\n",
      "  File \"pyarrow/_dataset.pyx\", line 3235, in pyarrow._dataset.Scanner.to_table\n",
      "  File \"pyarrow/error.pxi\", line 143, in pyarrow.lib.pyarrow_internal_check_status\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/spec.py\", line 1578, in read\n",
      "    out = self.cache._fetch(self.loc, self.loc + length)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/caching.py\", line 399, in _fetch\n",
      "    out = self.cache[offset : offset + end - start]\n",
      "MemoryError\n",
      "Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::deploy_ray_func()\u001b[39m (pid=24638, ip=172.31.27.60)\n",
      "  File \"/home/emr-notebook/.local/lib/python3.7/site-packages/modin/core/execution/ray/common/task_wrapper.py\", line 40, in deploy_ray_func\n",
      "  File \"/tmp/ray/session_2022-07-06_02-59-12_340846_29218/runtime_resources/pip/11ec394aa27dc2f92256e9847ec87567ef3cace5/virtualenv/lib/python3.7/site-packages/modin/core/storage_formats/pandas/parsers.py\", line 622, in parse\n",
      "    df = pandas.read_parquet(fname, **kwargs)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 500, in read_parquet\n",
      "    **kwargs,\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 240, in read\n",
      "    path_or_handle, columns=columns, **kwargs\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1942, in read_table\n",
      "    use_pandas_metadata=use_pandas_metadata)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1778, in read\n",
      "    use_threads=use_threads\n",
      "  File \"pyarrow/_dataset.pyx\", line 491, in pyarrow._dataset.Dataset.to_table\n",
      "  File \"pyarrow/_dataset.pyx\", line 3235, in pyarrow._dataset.Scanner.to_table\n",
      "  File \"pyarrow/error.pxi\", line 143, in pyarrow.lib.pyarrow_internal_check_status\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/spec.py\", line 1578, in read\n",
      "    out = self.cache._fetch(self.loc, self.loc + length)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/caching.py\", line 399, in _fetch\n",
      "    out = self.cache[offset : offset + end - start]\n",
      "MemoryError\n",
      "Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::deploy_ray_func()\u001b[39m (pid=24638, ip=172.31.27.60)\n",
      "  File \"/home/emr-notebook/.local/lib/python3.7/site-packages/modin/core/execution/ray/common/task_wrapper.py\", line 40, in deploy_ray_func\n",
      "  File \"/tmp/ray/session_2022-07-06_02-59-12_340846_29218/runtime_resources/pip/11ec394aa27dc2f92256e9847ec87567ef3cace5/virtualenv/lib/python3.7/site-packages/modin/core/storage_formats/pandas/parsers.py\", line 622, in parse\n",
      "    df = pandas.read_parquet(fname, **kwargs)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 500, in read_parquet\n",
      "    **kwargs,\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 240, in read\n",
      "    path_or_handle, columns=columns, **kwargs\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1942, in read_table\n",
      "    use_pandas_metadata=use_pandas_metadata)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1778, in read\n",
      "    use_threads=use_threads\n",
      "  File \"pyarrow/_dataset.pyx\", line 491, in pyarrow._dataset.Dataset.to_table\n",
      "  File \"pyarrow/_dataset.pyx\", line 3235, in pyarrow._dataset.Scanner.to_table\n",
      "  File \"pyarrow/error.pxi\", line 143, in pyarrow.lib.pyarrow_internal_check_status\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/spec.py\", line 1578, in read\n",
      "    out = self.cache._fetch(self.loc, self.loc + length)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/caching.py\", line 399, in _fetch\n",
      "    out = self.cache[offset : offset + end - start]\n",
      "MemoryError\n",
      "Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::deploy_ray_func()\u001b[39m (pid=24638, ip=172.31.27.60)\n",
      "  File \"/home/emr-notebook/.local/lib/python3.7/site-packages/modin/core/execution/ray/common/task_wrapper.py\", line 40, in deploy_ray_func\n",
      "  File \"/tmp/ray/session_2022-07-06_02-59-12_340846_29218/runtime_resources/pip/11ec394aa27dc2f92256e9847ec87567ef3cace5/virtualenv/lib/python3.7/site-packages/modin/core/storage_formats/pandas/parsers.py\", line 622, in parse\n",
      "    df = pandas.read_parquet(fname, **kwargs)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 500, in read_parquet\n",
      "    **kwargs,\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 240, in read\n",
      "    path_or_handle, columns=columns, **kwargs\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1942, in read_table\n",
      "    use_pandas_metadata=use_pandas_metadata)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1778, in read\n",
      "    use_threads=use_threads\n",
      "  File \"pyarrow/_dataset.pyx\", line 491, in pyarrow._dataset.Dataset.to_table\n",
      "  File \"pyarrow/_dataset.pyx\", line 3235, in pyarrow._dataset.Scanner.to_table\n",
      "  File \"pyarrow/error.pxi\", line 143, in pyarrow.lib.pyarrow_internal_check_status\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/spec.py\", line 1578, in read\n",
      "    out = self.cache._fetch(self.loc, self.loc + length)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/caching.py\", line 399, in _fetch\n",
      "    out = self.cache[offset : offset + end - start]\n",
      "MemoryError\n",
      "Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::deploy_ray_func()\u001b[39m (pid=24638, ip=172.31.27.60)\n",
      "  File \"/home/emr-notebook/.local/lib/python3.7/site-packages/modin/core/execution/ray/common/task_wrapper.py\", line 40, in deploy_ray_func\n",
      "  File \"/tmp/ray/session_2022-07-06_02-59-12_340846_29218/runtime_resources/pip/11ec394aa27dc2f92256e9847ec87567ef3cace5/virtualenv/lib/python3.7/site-packages/modin/core/storage_formats/pandas/parsers.py\", line 622, in parse\n",
      "    df = pandas.read_parquet(fname, **kwargs)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 500, in read_parquet\n",
      "    **kwargs,\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 240, in read\n",
      "    path_or_handle, columns=columns, **kwargs\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1942, in read_table\n",
      "    use_pandas_metadata=use_pandas_metadata)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1778, in read\n",
      "    use_threads=use_threads\n",
      "  File \"pyarrow/_dataset.pyx\", line 491, in pyarrow._dataset.Dataset.to_table\n",
      "  File \"pyarrow/_dataset.pyx\", line 3235, in pyarrow._dataset.Scanner.to_table\n",
      "  File \"pyarrow/error.pxi\", line 143, in pyarrow.lib.pyarrow_internal_check_status\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/spec.py\", line 1578, in read\n",
      "    out = self.cache._fetch(self.loc, self.loc + length)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/caching.py\", line 399, in _fetch\n",
      "    out = self.cache[offset : offset + end - start]\n",
      "MemoryError\n",
      "Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::deploy_ray_func()\u001b[39m (pid=24638, ip=172.31.27.60)\n",
      "  File \"/home/emr-notebook/.local/lib/python3.7/site-packages/modin/core/execution/ray/common/task_wrapper.py\", line 40, in deploy_ray_func\n",
      "  File \"/tmp/ray/session_2022-07-06_02-59-12_340846_29218/runtime_resources/pip/11ec394aa27dc2f92256e9847ec87567ef3cace5/virtualenv/lib/python3.7/site-packages/modin/core/storage_formats/pandas/parsers.py\", line 622, in parse\n",
      "    df = pandas.read_parquet(fname, **kwargs)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 500, in read_parquet\n",
      "    **kwargs,\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 240, in read\n",
      "    path_or_handle, columns=columns, **kwargs\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1942, in read_table\n",
      "    use_pandas_metadata=use_pandas_metadata)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1778, in read\n",
      "    use_threads=use_threads\n",
      "  File \"pyarrow/_dataset.pyx\", line 491, in pyarrow._dataset.Dataset.to_table\n",
      "  File \"pyarrow/_dataset.pyx\", line 3235, in pyarrow._dataset.Scanner.to_table\n",
      "  File \"pyarrow/error.pxi\", line 143, in pyarrow.lib.pyarrow_internal_check_status\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/spec.py\", line 1578, in read\n",
      "    out = self.cache._fetch(self.loc, self.loc + length)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/caching.py\", line 399, in _fetch\n",
      "    out = self.cache[offset : offset + end - start]\n",
      "MemoryError\n",
      "Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::deploy_ray_func()\u001b[39m (pid=24638, ip=172.31.27.60)\n",
      "  File \"/home/emr-notebook/.local/lib/python3.7/site-packages/modin/core/execution/ray/common/task_wrapper.py\", line 40, in deploy_ray_func\n",
      "  File \"/tmp/ray/session_2022-07-06_02-59-12_340846_29218/runtime_resources/pip/11ec394aa27dc2f92256e9847ec87567ef3cace5/virtualenv/lib/python3.7/site-packages/modin/core/storage_formats/pandas/parsers.py\", line 622, in parse\n",
      "    df = pandas.read_parquet(fname, **kwargs)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 500, in read_parquet\n",
      "    **kwargs,\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 240, in read\n",
      "    path_or_handle, columns=columns, **kwargs\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1942, in read_table\n",
      "    use_pandas_metadata=use_pandas_metadata)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1778, in read\n",
      "    use_threads=use_threads\n",
      "  File \"pyarrow/_dataset.pyx\", line 491, in pyarrow._dataset.Dataset.to_table\n",
      "  File \"pyarrow/_dataset.pyx\", line 3235, in pyarrow._dataset.Scanner.to_table\n",
      "  File \"pyarrow/error.pxi\", line 143, in pyarrow.lib.pyarrow_internal_check_status\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/spec.py\", line 1578, in read\n",
      "    out = self.cache._fetch(self.loc, self.loc + length)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/caching.py\", line 399, in _fetch\n",
      "    out = self.cache[offset : offset + end - start]\n",
      "MemoryError\n",
      "Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::deploy_ray_func()\u001b[39m (pid=24638, ip=172.31.27.60)\n",
      "  File \"/home/emr-notebook/.local/lib/python3.7/site-packages/modin/core/execution/ray/common/task_wrapper.py\", line 40, in deploy_ray_func\n",
      "  File \"/tmp/ray/session_2022-07-06_02-59-12_340846_29218/runtime_resources/pip/11ec394aa27dc2f92256e9847ec87567ef3cace5/virtualenv/lib/python3.7/site-packages/modin/core/storage_formats/pandas/parsers.py\", line 622, in parse\n",
      "    df = pandas.read_parquet(fname, **kwargs)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 500, in read_parquet\n",
      "    **kwargs,\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 240, in read\n",
      "    path_or_handle, columns=columns, **kwargs\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1942, in read_table\n",
      "    use_pandas_metadata=use_pandas_metadata)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1778, in read\n",
      "    use_threads=use_threads\n",
      "  File \"pyarrow/_dataset.pyx\", line 491, in pyarrow._dataset.Dataset.to_table\n",
      "  File \"pyarrow/_dataset.pyx\", line 3235, in pyarrow._dataset.Scanner.to_table\n",
      "  File \"pyarrow/error.pxi\", line 143, in pyarrow.lib.pyarrow_internal_check_status\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/spec.py\", line 1578, in read\n",
      "    out = self.cache._fetch(self.loc, self.loc + length)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/caching.py\", line 399, in _fetch\n",
      "    out = self.cache[offset : offset + end - start]\n",
      "MemoryError\n",
      "Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::deploy_ray_func()\u001b[39m (pid=24638, ip=172.31.27.60)\n",
      "  File \"/home/emr-notebook/.local/lib/python3.7/site-packages/modin/core/execution/ray/common/task_wrapper.py\", line 40, in deploy_ray_func\n",
      "  File \"/tmp/ray/session_2022-07-06_02-59-12_340846_29218/runtime_resources/pip/11ec394aa27dc2f92256e9847ec87567ef3cace5/virtualenv/lib/python3.7/site-packages/modin/core/storage_formats/pandas/parsers.py\", line 622, in parse\n",
      "    df = pandas.read_parquet(fname, **kwargs)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 500, in read_parquet\n",
      "    **kwargs,\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 240, in read\n",
      "    path_or_handle, columns=columns, **kwargs\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1942, in read_table\n",
      "    use_pandas_metadata=use_pandas_metadata)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1778, in read\n",
      "    use_threads=use_threads\n",
      "  File \"pyarrow/_dataset.pyx\", line 491, in pyarrow._dataset.Dataset.to_table\n",
      "  File \"pyarrow/_dataset.pyx\", line 3235, in pyarrow._dataset.Scanner.to_table\n",
      "  File \"pyarrow/error.pxi\", line 143, in pyarrow.lib.pyarrow_internal_check_status\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/spec.py\", line 1578, in read\n",
      "    out = self.cache._fetch(self.loc, self.loc + length)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/caching.py\", line 399, in _fetch\n",
      "    out = self.cache[offset : offset + end - start]\n",
      "MemoryError\n",
      "Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::deploy_ray_func()\u001b[39m (pid=24638, ip=172.31.27.60)\n",
      "  File \"/home/emr-notebook/.local/lib/python3.7/site-packages/modin/core/execution/ray/common/task_wrapper.py\", line 40, in deploy_ray_func\n",
      "  File \"/tmp/ray/session_2022-07-06_02-59-12_340846_29218/runtime_resources/pip/11ec394aa27dc2f92256e9847ec87567ef3cace5/virtualenv/lib/python3.7/site-packages/modin/core/storage_formats/pandas/parsers.py\", line 622, in parse\n",
      "    df = pandas.read_parquet(fname, **kwargs)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 500, in read_parquet\n",
      "    **kwargs,\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 240, in read\n",
      "    path_or_handle, columns=columns, **kwargs\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1942, in read_table\n",
      "    use_pandas_metadata=use_pandas_metadata)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1778, in read\n",
      "    use_threads=use_threads\n",
      "  File \"pyarrow/_dataset.pyx\", line 491, in pyarrow._dataset.Dataset.to_table\n",
      "  File \"pyarrow/_dataset.pyx\", line 3235, in pyarrow._dataset.Scanner.to_table\n",
      "  File \"pyarrow/error.pxi\", line 143, in pyarrow.lib.pyarrow_internal_check_status\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/spec.py\", line 1578, in read\n",
      "    out = self.cache._fetch(self.loc, self.loc + length)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/caching.py\", line 399, in _fetch\n",
      "    out = self.cache[offset : offset + end - start]\n",
      "MemoryError\n",
      "Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::deploy_ray_func()\u001b[39m (pid=24638, ip=172.31.27.60)\n",
      "  File \"/home/emr-notebook/.local/lib/python3.7/site-packages/modin/core/execution/ray/common/task_wrapper.py\", line 40, in deploy_ray_func\n",
      "  File \"/tmp/ray/session_2022-07-06_02-59-12_340846_29218/runtime_resources/pip/11ec394aa27dc2f92256e9847ec87567ef3cace5/virtualenv/lib/python3.7/site-packages/modin/core/storage_formats/pandas/parsers.py\", line 622, in parse\n",
      "    df = pandas.read_parquet(fname, **kwargs)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 500, in read_parquet\n",
      "    **kwargs,\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 240, in read\n",
      "    path_or_handle, columns=columns, **kwargs\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1942, in read_table\n",
      "    use_pandas_metadata=use_pandas_metadata)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1778, in read\n",
      "    use_threads=use_threads\n",
      "  File \"pyarrow/_dataset.pyx\", line 491, in pyarrow._dataset.Dataset.to_table\n",
      "  File \"pyarrow/_dataset.pyx\", line 3235, in pyarrow._dataset.Scanner.to_table\n",
      "  File \"pyarrow/error.pxi\", line 143, in pyarrow.lib.pyarrow_internal_check_status\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/spec.py\", line 1578, in read\n",
      "    out = self.cache._fetch(self.loc, self.loc + length)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/caching.py\", line 399, in _fetch\n",
      "    out = self.cache[offset : offset + end - start]\n",
      "MemoryError\n",
      "Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::deploy_ray_func()\u001b[39m (pid=24638, ip=172.31.27.60)\n",
      "  File \"/home/emr-notebook/.local/lib/python3.7/site-packages/modin/core/execution/ray/common/task_wrapper.py\", line 40, in deploy_ray_func\n",
      "  File \"/tmp/ray/session_2022-07-06_02-59-12_340846_29218/runtime_resources/pip/11ec394aa27dc2f92256e9847ec87567ef3cace5/virtualenv/lib/python3.7/site-packages/modin/core/storage_formats/pandas/parsers.py\", line 622, in parse\n",
      "    df = pandas.read_parquet(fname, **kwargs)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 500, in read_parquet\n",
      "    **kwargs,\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 240, in read\n",
      "    path_or_handle, columns=columns, **kwargs\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1942, in read_table\n",
      "    use_pandas_metadata=use_pandas_metadata)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1778, in read\n",
      "    use_threads=use_threads\n",
      "  File \"pyarrow/_dataset.pyx\", line 491, in pyarrow._dataset.Dataset.to_table\n",
      "  File \"pyarrow/_dataset.pyx\", line 3235, in pyarrow._dataset.Scanner.to_table\n",
      "  File \"pyarrow/error.pxi\", line 143, in pyarrow.lib.pyarrow_internal_check_status\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/spec.py\", line 1578, in read\n",
      "    out = self.cache._fetch(self.loc, self.loc + length)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/caching.py\", line 399, in _fetch\n",
      "    out = self.cache[offset : offset + end - start]\n",
      "MemoryError\n",
      "Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::deploy_ray_func()\u001b[39m (pid=24638, ip=172.31.27.60)\n",
      "  File \"/home/emr-notebook/.local/lib/python3.7/site-packages/modin/core/execution/ray/common/task_wrapper.py\", line 40, in deploy_ray_func\n",
      "  File \"/tmp/ray/session_2022-07-06_02-59-12_340846_29218/runtime_resources/pip/11ec394aa27dc2f92256e9847ec87567ef3cace5/virtualenv/lib/python3.7/site-packages/modin/core/storage_formats/pandas/parsers.py\", line 622, in parse\n",
      "    df = pandas.read_parquet(fname, **kwargs)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 500, in read_parquet\n",
      "    **kwargs,\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 240, in read\n",
      "    path_or_handle, columns=columns, **kwargs\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1942, in read_table\n",
      "    use_pandas_metadata=use_pandas_metadata)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1778, in read\n",
      "    use_threads=use_threads\n",
      "  File \"pyarrow/_dataset.pyx\", line 491, in pyarrow._dataset.Dataset.to_table\n",
      "  File \"pyarrow/_dataset.pyx\", line 3235, in pyarrow._dataset.Scanner.to_table\n",
      "  File \"pyarrow/error.pxi\", line 143, in pyarrow.lib.pyarrow_internal_check_status\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/spec.py\", line 1578, in read\n",
      "    out = self.cache._fetch(self.loc, self.loc + length)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/caching.py\", line 399, in _fetch\n",
      "    out = self.cache[offset : offset + end - start]\n",
      "MemoryError\n",
      "Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::deploy_ray_func()\u001b[39m (pid=24638, ip=172.31.27.60)\n",
      "  File \"/home/emr-notebook/.local/lib/python3.7/site-packages/modin/core/execution/ray/common/task_wrapper.py\", line 40, in deploy_ray_func\n",
      "  File \"/tmp/ray/session_2022-07-06_02-59-12_340846_29218/runtime_resources/pip/11ec394aa27dc2f92256e9847ec87567ef3cace5/virtualenv/lib/python3.7/site-packages/modin/core/storage_formats/pandas/parsers.py\", line 622, in parse\n",
      "    df = pandas.read_parquet(fname, **kwargs)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 500, in read_parquet\n",
      "    **kwargs,\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 240, in read\n",
      "    path_or_handle, columns=columns, **kwargs\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1942, in read_table\n",
      "    use_pandas_metadata=use_pandas_metadata)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1778, in read\n",
      "    use_threads=use_threads\n",
      "  File \"pyarrow/_dataset.pyx\", line 491, in pyarrow._dataset.Dataset.to_table\n",
      "  File \"pyarrow/_dataset.pyx\", line 3235, in pyarrow._dataset.Scanner.to_table\n",
      "  File \"pyarrow/error.pxi\", line 143, in pyarrow.lib.pyarrow_internal_check_status\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/spec.py\", line 1578, in read\n",
      "    out = self.cache._fetch(self.loc, self.loc + length)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/caching.py\", line 399, in _fetch\n",
      "    out = self.cache[offset : offset + end - start]\n",
      "MemoryError\n",
      "Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::deploy_ray_func()\u001b[39m (pid=24638, ip=172.31.27.60)\n",
      "  File \"/home/emr-notebook/.local/lib/python3.7/site-packages/modin/core/execution/ray/common/task_wrapper.py\", line 40, in deploy_ray_func\n",
      "  File \"/tmp/ray/session_2022-07-06_02-59-12_340846_29218/runtime_resources/pip/11ec394aa27dc2f92256e9847ec87567ef3cace5/virtualenv/lib/python3.7/site-packages/modin/core/storage_formats/pandas/parsers.py\", line 622, in parse\n",
      "    df = pandas.read_parquet(fname, **kwargs)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 500, in read_parquet\n",
      "    **kwargs,\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 240, in read\n",
      "    path_or_handle, columns=columns, **kwargs\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1942, in read_table\n",
      "    use_pandas_metadata=use_pandas_metadata)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1778, in read\n",
      "    use_threads=use_threads\n",
      "  File \"pyarrow/_dataset.pyx\", line 491, in pyarrow._dataset.Dataset.to_table\n",
      "  File \"pyarrow/_dataset.pyx\", line 3235, in pyarrow._dataset.Scanner.to_table\n",
      "  File \"pyarrow/error.pxi\", line 143, in pyarrow.lib.pyarrow_internal_check_status\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/spec.py\", line 1578, in read\n",
      "    out = self.cache._fetch(self.loc, self.loc + length)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/caching.py\", line 399, in _fetch\n",
      "    out = self.cache[offset : offset + end - start]\n",
      "MemoryError\n",
      "Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::deploy_ray_func()\u001b[39m (pid=24638, ip=172.31.27.60)\n",
      "  File \"/home/emr-notebook/.local/lib/python3.7/site-packages/modin/core/execution/ray/common/task_wrapper.py\", line 40, in deploy_ray_func\n",
      "  File \"/tmp/ray/session_2022-07-06_02-59-12_340846_29218/runtime_resources/pip/11ec394aa27dc2f92256e9847ec87567ef3cace5/virtualenv/lib/python3.7/site-packages/modin/core/storage_formats/pandas/parsers.py\", line 622, in parse\n",
      "    df = pandas.read_parquet(fname, **kwargs)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 500, in read_parquet\n",
      "    **kwargs,\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 240, in read\n",
      "    path_or_handle, columns=columns, **kwargs\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1942, in read_table\n",
      "    use_pandas_metadata=use_pandas_metadata)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1778, in read\n",
      "    use_threads=use_threads\n",
      "  File \"pyarrow/_dataset.pyx\", line 491, in pyarrow._dataset.Dataset.to_table\n",
      "  File \"pyarrow/_dataset.pyx\", line 3235, in pyarrow._dataset.Scanner.to_table\n",
      "  File \"pyarrow/error.pxi\", line 143, in pyarrow.lib.pyarrow_internal_check_status\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/spec.py\", line 1578, in read\n",
      "    out = self.cache._fetch(self.loc, self.loc + length)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/caching.py\", line 399, in _fetch\n",
      "    out = self.cache[offset : offset + end - start]\n",
      "MemoryError\n",
      "Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::deploy_ray_func()\u001b[39m (pid=24638, ip=172.31.27.60)\n",
      "  File \"/home/emr-notebook/.local/lib/python3.7/site-packages/modin/core/execution/ray/common/task_wrapper.py\", line 40, in deploy_ray_func\n",
      "  File \"/tmp/ray/session_2022-07-06_02-59-12_340846_29218/runtime_resources/pip/11ec394aa27dc2f92256e9847ec87567ef3cace5/virtualenv/lib/python3.7/site-packages/modin/core/storage_formats/pandas/parsers.py\", line 622, in parse\n",
      "    df = pandas.read_parquet(fname, **kwargs)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 500, in read_parquet\n",
      "    **kwargs,\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 240, in read\n",
      "    path_or_handle, columns=columns, **kwargs\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1942, in read_table\n",
      "    use_pandas_metadata=use_pandas_metadata)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1778, in read\n",
      "    use_threads=use_threads\n",
      "  File \"pyarrow/_dataset.pyx\", line 491, in pyarrow._dataset.Dataset.to_table\n",
      "  File \"pyarrow/_dataset.pyx\", line 3235, in pyarrow._dataset.Scanner.to_table\n",
      "  File \"pyarrow/error.pxi\", line 143, in pyarrow.lib.pyarrow_internal_check_status\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/spec.py\", line 1578, in read\n",
      "    out = self.cache._fetch(self.loc, self.loc + length)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/caching.py\", line 399, in _fetch\n",
      "    out = self.cache[offset : offset + end - start]\n",
      "MemoryError\n",
      "Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::deploy_ray_func()\u001b[39m (pid=24638, ip=172.31.27.60)\n",
      "  File \"/home/emr-notebook/.local/lib/python3.7/site-packages/modin/core/execution/ray/common/task_wrapper.py\", line 40, in deploy_ray_func\n",
      "  File \"/tmp/ray/session_2022-07-06_02-59-12_340846_29218/runtime_resources/pip/11ec394aa27dc2f92256e9847ec87567ef3cace5/virtualenv/lib/python3.7/site-packages/modin/core/storage_formats/pandas/parsers.py\", line 622, in parse\n",
      "    df = pandas.read_parquet(fname, **kwargs)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 500, in read_parquet\n",
      "    **kwargs,\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 240, in read\n",
      "    path_or_handle, columns=columns, **kwargs\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1942, in read_table\n",
      "    use_pandas_metadata=use_pandas_metadata)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1778, in read\n",
      "    use_threads=use_threads\n",
      "  File \"pyarrow/_dataset.pyx\", line 491, in pyarrow._dataset.Dataset.to_table\n",
      "  File \"pyarrow/_dataset.pyx\", line 3235, in pyarrow._dataset.Scanner.to_table\n",
      "  File \"pyarrow/error.pxi\", line 143, in pyarrow.lib.pyarrow_internal_check_status\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/spec.py\", line 1578, in read\n",
      "    out = self.cache._fetch(self.loc, self.loc + length)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/caching.py\", line 399, in _fetch\n",
      "    out = self.cache[offset : offset + end - start]\n",
      "MemoryError\n",
      "Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::deploy_ray_func()\u001b[39m (pid=24638, ip=172.31.27.60)\n",
      "  File \"/home/emr-notebook/.local/lib/python3.7/site-packages/modin/core/execution/ray/common/task_wrapper.py\", line 40, in deploy_ray_func\n",
      "  File \"/tmp/ray/session_2022-07-06_02-59-12_340846_29218/runtime_resources/pip/11ec394aa27dc2f92256e9847ec87567ef3cace5/virtualenv/lib/python3.7/site-packages/modin/core/storage_formats/pandas/parsers.py\", line 622, in parse\n",
      "    df = pandas.read_parquet(fname, **kwargs)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 500, in read_parquet\n",
      "    **kwargs,\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 240, in read\n",
      "    path_or_handle, columns=columns, **kwargs\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1942, in read_table\n",
      "    use_pandas_metadata=use_pandas_metadata)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1778, in read\n",
      "    use_threads=use_threads\n",
      "  File \"pyarrow/_dataset.pyx\", line 491, in pyarrow._dataset.Dataset.to_table\n",
      "  File \"pyarrow/_dataset.pyx\", line 3235, in pyarrow._dataset.Scanner.to_table\n",
      "  File \"pyarrow/error.pxi\", line 143, in pyarrow.lib.pyarrow_internal_check_status\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/spec.py\", line 1578, in read\n",
      "    out = self.cache._fetch(self.loc, self.loc + length)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/caching.py\", line 399, in _fetch\n",
      "    out = self.cache[offset : offset + end - start]\n",
      "MemoryError\n",
      "Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::deploy_ray_func()\u001b[39m (pid=24638, ip=172.31.27.60)\n",
      "  File \"/home/emr-notebook/.local/lib/python3.7/site-packages/modin/core/execution/ray/common/task_wrapper.py\", line 40, in deploy_ray_func\n",
      "  File \"/tmp/ray/session_2022-07-06_02-59-12_340846_29218/runtime_resources/pip/11ec394aa27dc2f92256e9847ec87567ef3cace5/virtualenv/lib/python3.7/site-packages/modin/core/storage_formats/pandas/parsers.py\", line 622, in parse\n",
      "    df = pandas.read_parquet(fname, **kwargs)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 500, in read_parquet\n",
      "    **kwargs,\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 240, in read\n",
      "    path_or_handle, columns=columns, **kwargs\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1942, in read_table\n",
      "    use_pandas_metadata=use_pandas_metadata)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1778, in read\n",
      "    use_threads=use_threads\n",
      "  File \"pyarrow/_dataset.pyx\", line 491, in pyarrow._dataset.Dataset.to_table\n",
      "  File \"pyarrow/_dataset.pyx\", line 3235, in pyarrow._dataset.Scanner.to_table\n",
      "  File \"pyarrow/error.pxi\", line 143, in pyarrow.lib.pyarrow_internal_check_status\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/spec.py\", line 1578, in read\n",
      "    out = self.cache._fetch(self.loc, self.loc + length)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/caching.py\", line 399, in _fetch\n",
      "    out = self.cache[offset : offset + end - start]\n",
      "MemoryError\n",
      "Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::deploy_ray_func()\u001b[39m (pid=24638, ip=172.31.27.60)\n",
      "  File \"/home/emr-notebook/.local/lib/python3.7/site-packages/modin/core/execution/ray/common/task_wrapper.py\", line 40, in deploy_ray_func\n",
      "  File \"/tmp/ray/session_2022-07-06_02-59-12_340846_29218/runtime_resources/pip/11ec394aa27dc2f92256e9847ec87567ef3cace5/virtualenv/lib/python3.7/site-packages/modin/core/storage_formats/pandas/parsers.py\", line 622, in parse\n",
      "    df = pandas.read_parquet(fname, **kwargs)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 500, in read_parquet\n",
      "    **kwargs,\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 240, in read\n",
      "    path_or_handle, columns=columns, **kwargs\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1942, in read_table\n",
      "    use_pandas_metadata=use_pandas_metadata)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1778, in read\n",
      "    use_threads=use_threads\n",
      "  File \"pyarrow/_dataset.pyx\", line 491, in pyarrow._dataset.Dataset.to_table\n",
      "  File \"pyarrow/_dataset.pyx\", line 3235, in pyarrow._dataset.Scanner.to_table\n",
      "  File \"pyarrow/error.pxi\", line 143, in pyarrow.lib.pyarrow_internal_check_status\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/spec.py\", line 1578, in read\n",
      "    out = self.cache._fetch(self.loc, self.loc + length)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/caching.py\", line 399, in _fetch\n",
      "    out = self.cache[offset : offset + end - start]\n",
      "MemoryError\n",
      "Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::deploy_ray_func()\u001b[39m (pid=24638, ip=172.31.27.60)\n",
      "  File \"/home/emr-notebook/.local/lib/python3.7/site-packages/modin/core/execution/ray/common/task_wrapper.py\", line 40, in deploy_ray_func\n",
      "  File \"/tmp/ray/session_2022-07-06_02-59-12_340846_29218/runtime_resources/pip/11ec394aa27dc2f92256e9847ec87567ef3cace5/virtualenv/lib/python3.7/site-packages/modin/core/storage_formats/pandas/parsers.py\", line 622, in parse\n",
      "    df = pandas.read_parquet(fname, **kwargs)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 500, in read_parquet\n",
      "    **kwargs,\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 240, in read\n",
      "    path_or_handle, columns=columns, **kwargs\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1942, in read_table\n",
      "    use_pandas_metadata=use_pandas_metadata)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1778, in read\n",
      "    use_threads=use_threads\n",
      "  File \"pyarrow/_dataset.pyx\", line 491, in pyarrow._dataset.Dataset.to_table\n",
      "  File \"pyarrow/_dataset.pyx\", line 3235, in pyarrow._dataset.Scanner.to_table\n",
      "  File \"pyarrow/error.pxi\", line 143, in pyarrow.lib.pyarrow_internal_check_status\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/spec.py\", line 1578, in read\n",
      "    out = self.cache._fetch(self.loc, self.loc + length)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/caching.py\", line 399, in _fetch\n",
      "    out = self.cache[offset : offset + end - start]\n",
      "MemoryError\n",
      "Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::deploy_ray_func()\u001b[39m (pid=24638, ip=172.31.27.60)\n",
      "  File \"/home/emr-notebook/.local/lib/python3.7/site-packages/modin/core/execution/ray/common/task_wrapper.py\", line 40, in deploy_ray_func\n",
      "  File \"/tmp/ray/session_2022-07-06_02-59-12_340846_29218/runtime_resources/pip/11ec394aa27dc2f92256e9847ec87567ef3cace5/virtualenv/lib/python3.7/site-packages/modin/core/storage_formats/pandas/parsers.py\", line 622, in parse\n",
      "    df = pandas.read_parquet(fname, **kwargs)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 500, in read_parquet\n",
      "    **kwargs,\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 240, in read\n",
      "    path_or_handle, columns=columns, **kwargs\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1942, in read_table\n",
      "    use_pandas_metadata=use_pandas_metadata)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1778, in read\n",
      "    use_threads=use_threads\n",
      "  File \"pyarrow/_dataset.pyx\", line 491, in pyarrow._dataset.Dataset.to_table\n",
      "  File \"pyarrow/_dataset.pyx\", line 3235, in pyarrow._dataset.Scanner.to_table\n",
      "  File \"pyarrow/error.pxi\", line 143, in pyarrow.lib.pyarrow_internal_check_status\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/spec.py\", line 1578, in read\n",
      "    out = self.cache._fetch(self.loc, self.loc + length)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/caching.py\", line 399, in _fetch\n",
      "    out = self.cache[offset : offset + end - start]\n",
      "MemoryError\n",
      "Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::deploy_ray_func()\u001b[39m (pid=24638, ip=172.31.27.60)\n",
      "  File \"/home/emr-notebook/.local/lib/python3.7/site-packages/modin/core/execution/ray/common/task_wrapper.py\", line 40, in deploy_ray_func\n",
      "  File \"/tmp/ray/session_2022-07-06_02-59-12_340846_29218/runtime_resources/pip/11ec394aa27dc2f92256e9847ec87567ef3cace5/virtualenv/lib/python3.7/site-packages/modin/core/storage_formats/pandas/parsers.py\", line 622, in parse\n",
      "    df = pandas.read_parquet(fname, **kwargs)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 500, in read_parquet\n",
      "    **kwargs,\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 240, in read\n",
      "    path_or_handle, columns=columns, **kwargs\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1942, in read_table\n",
      "    use_pandas_metadata=use_pandas_metadata)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1778, in read\n",
      "    use_threads=use_threads\n",
      "  File \"pyarrow/_dataset.pyx\", line 491, in pyarrow._dataset.Dataset.to_table\n",
      "  File \"pyarrow/_dataset.pyx\", line 3235, in pyarrow._dataset.Scanner.to_table\n",
      "  File \"pyarrow/error.pxi\", line 143, in pyarrow.lib.pyarrow_internal_check_status\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/spec.py\", line 1578, in read\n",
      "    out = self.cache._fetch(self.loc, self.loc + length)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/caching.py\", line 399, in _fetch\n",
      "    out = self.cache[offset : offset + end - start]\n",
      "MemoryError\n",
      "Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::deploy_ray_func()\u001b[39m (pid=24638, ip=172.31.27.60)\n",
      "  File \"/home/emr-notebook/.local/lib/python3.7/site-packages/modin/core/execution/ray/common/task_wrapper.py\", line 40, in deploy_ray_func\n",
      "  File \"/tmp/ray/session_2022-07-06_02-59-12_340846_29218/runtime_resources/pip/11ec394aa27dc2f92256e9847ec87567ef3cace5/virtualenv/lib/python3.7/site-packages/modin/core/storage_formats/pandas/parsers.py\", line 622, in parse\n",
      "    df = pandas.read_parquet(fname, **kwargs)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 500, in read_parquet\n",
      "    **kwargs,\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 240, in read\n",
      "    path_or_handle, columns=columns, **kwargs\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1942, in read_table\n",
      "    use_pandas_metadata=use_pandas_metadata)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1778, in read\n",
      "    use_threads=use_threads\n",
      "  File \"pyarrow/_dataset.pyx\", line 491, in pyarrow._dataset.Dataset.to_table\n",
      "  File \"pyarrow/_dataset.pyx\", line 3235, in pyarrow._dataset.Scanner.to_table\n",
      "  File \"pyarrow/error.pxi\", line 143, in pyarrow.lib.pyarrow_internal_check_status\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/spec.py\", line 1578, in read\n",
      "    out = self.cache._fetch(self.loc, self.loc + length)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/caching.py\", line 399, in _fetch\n",
      "    out = self.cache[offset : offset + end - start]\n",
      "MemoryError\n",
      "Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::deploy_ray_func()\u001b[39m (pid=24638, ip=172.31.27.60)\n",
      "  File \"/home/emr-notebook/.local/lib/python3.7/site-packages/modin/core/execution/ray/common/task_wrapper.py\", line 40, in deploy_ray_func\n",
      "  File \"/tmp/ray/session_2022-07-06_02-59-12_340846_29218/runtime_resources/pip/11ec394aa27dc2f92256e9847ec87567ef3cace5/virtualenv/lib/python3.7/site-packages/modin/core/storage_formats/pandas/parsers.py\", line 622, in parse\n",
      "    df = pandas.read_parquet(fname, **kwargs)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 500, in read_parquet\n",
      "    **kwargs,\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 240, in read\n",
      "    path_or_handle, columns=columns, **kwargs\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1942, in read_table\n",
      "    use_pandas_metadata=use_pandas_metadata)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1778, in read\n",
      "    use_threads=use_threads\n",
      "  File \"pyarrow/_dataset.pyx\", line 491, in pyarrow._dataset.Dataset.to_table\n",
      "  File \"pyarrow/_dataset.pyx\", line 3235, in pyarrow._dataset.Scanner.to_table\n",
      "  File \"pyarrow/error.pxi\", line 143, in pyarrow.lib.pyarrow_internal_check_status\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/spec.py\", line 1578, in read\n",
      "    out = self.cache._fetch(self.loc, self.loc + length)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/caching.py\", line 399, in _fetch\n",
      "    out = self.cache[offset : offset + end - start]\n",
      "MemoryError\n",
      "Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::deploy_ray_func()\u001b[39m (pid=24638, ip=172.31.27.60)\n",
      "  File \"/home/emr-notebook/.local/lib/python3.7/site-packages/modin/core/execution/ray/common/task_wrapper.py\", line 40, in deploy_ray_func\n",
      "  File \"/tmp/ray/session_2022-07-06_02-59-12_340846_29218/runtime_resources/pip/11ec394aa27dc2f92256e9847ec87567ef3cace5/virtualenv/lib/python3.7/site-packages/modin/core/storage_formats/pandas/parsers.py\", line 622, in parse\n",
      "    df = pandas.read_parquet(fname, **kwargs)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 500, in read_parquet\n",
      "    **kwargs,\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 240, in read\n",
      "    path_or_handle, columns=columns, **kwargs\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1942, in read_table\n",
      "    use_pandas_metadata=use_pandas_metadata)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1778, in read\n",
      "    use_threads=use_threads\n",
      "  File \"pyarrow/_dataset.pyx\", line 491, in pyarrow._dataset.Dataset.to_table\n",
      "  File \"pyarrow/_dataset.pyx\", line 3235, in pyarrow._dataset.Scanner.to_table\n",
      "  File \"pyarrow/error.pxi\", line 143, in pyarrow.lib.pyarrow_internal_check_status\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/spec.py\", line 1578, in read\n",
      "    out = self.cache._fetch(self.loc, self.loc + length)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/caching.py\", line 399, in _fetch\n",
      "    out = self.cache[offset : offset + end - start]\n",
      "MemoryError\n",
      "Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::deploy_ray_func()\u001b[39m (pid=24638, ip=172.31.27.60)\n",
      "  File \"/home/emr-notebook/.local/lib/python3.7/site-packages/modin/core/execution/ray/common/task_wrapper.py\", line 40, in deploy_ray_func\n",
      "  File \"/tmp/ray/session_2022-07-06_02-59-12_340846_29218/runtime_resources/pip/11ec394aa27dc2f92256e9847ec87567ef3cace5/virtualenv/lib/python3.7/site-packages/modin/core/storage_formats/pandas/parsers.py\", line 622, in parse\n",
      "    df = pandas.read_parquet(fname, **kwargs)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 500, in read_parquet\n",
      "    **kwargs,\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 240, in read\n",
      "    path_or_handle, columns=columns, **kwargs\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1942, in read_table\n",
      "    use_pandas_metadata=use_pandas_metadata)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1778, in read\n",
      "    use_threads=use_threads\n",
      "  File \"pyarrow/_dataset.pyx\", line 491, in pyarrow._dataset.Dataset.to_table\n",
      "  File \"pyarrow/_dataset.pyx\", line 3235, in pyarrow._dataset.Scanner.to_table\n",
      "  File \"pyarrow/error.pxi\", line 143, in pyarrow.lib.pyarrow_internal_check_status\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/spec.py\", line 1578, in read\n",
      "    out = self.cache._fetch(self.loc, self.loc + length)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/caching.py\", line 399, in _fetch\n",
      "    out = self.cache[offset : offset + end - start]\n",
      "MemoryError\n",
      "Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::deploy_ray_func()\u001b[39m (pid=24638, ip=172.31.27.60)\n",
      "  File \"/home/emr-notebook/.local/lib/python3.7/site-packages/modin/core/execution/ray/common/task_wrapper.py\", line 40, in deploy_ray_func\n",
      "  File \"/tmp/ray/session_2022-07-06_02-59-12_340846_29218/runtime_resources/pip/11ec394aa27dc2f92256e9847ec87567ef3cace5/virtualenv/lib/python3.7/site-packages/modin/core/storage_formats/pandas/parsers.py\", line 622, in parse\n",
      "    df = pandas.read_parquet(fname, **kwargs)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 500, in read_parquet\n",
      "    **kwargs,\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 240, in read\n",
      "    path_or_handle, columns=columns, **kwargs\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1942, in read_table\n",
      "    use_pandas_metadata=use_pandas_metadata)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1778, in read\n",
      "    use_threads=use_threads\n",
      "  File \"pyarrow/_dataset.pyx\", line 491, in pyarrow._dataset.Dataset.to_table\n",
      "  File \"pyarrow/_dataset.pyx\", line 3235, in pyarrow._dataset.Scanner.to_table\n",
      "  File \"pyarrow/error.pxi\", line 143, in pyarrow.lib.pyarrow_internal_check_status\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/spec.py\", line 1578, in read\n",
      "    out = self.cache._fetch(self.loc, self.loc + length)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/caching.py\", line 399, in _fetch\n",
      "    out = self.cache[offset : offset + end - start]\n",
      "MemoryError\n",
      "Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::deploy_ray_func()\u001b[39m (pid=24638, ip=172.31.27.60)\n",
      "  File \"/home/emr-notebook/.local/lib/python3.7/site-packages/modin/core/execution/ray/common/task_wrapper.py\", line 40, in deploy_ray_func\n",
      "  File \"/tmp/ray/session_2022-07-06_02-59-12_340846_29218/runtime_resources/pip/11ec394aa27dc2f92256e9847ec87567ef3cace5/virtualenv/lib/python3.7/site-packages/modin/core/storage_formats/pandas/parsers.py\", line 622, in parse\n",
      "    df = pandas.read_parquet(fname, **kwargs)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 500, in read_parquet\n",
      "    **kwargs,\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 240, in read\n",
      "    path_or_handle, columns=columns, **kwargs\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1942, in read_table\n",
      "    use_pandas_metadata=use_pandas_metadata)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1778, in read\n",
      "    use_threads=use_threads\n",
      "  File \"pyarrow/_dataset.pyx\", line 491, in pyarrow._dataset.Dataset.to_table\n",
      "  File \"pyarrow/_dataset.pyx\", line 3235, in pyarrow._dataset.Scanner.to_table\n",
      "  File \"pyarrow/error.pxi\", line 143, in pyarrow.lib.pyarrow_internal_check_status\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/spec.py\", line 1578, in read\n",
      "    out = self.cache._fetch(self.loc, self.loc + length)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/caching.py\", line 399, in _fetch\n",
      "    out = self.cache[offset : offset + end - start]\n",
      "MemoryError\n",
      "Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::deploy_ray_func()\u001b[39m (pid=24638, ip=172.31.27.60)\n",
      "  File \"/home/emr-notebook/.local/lib/python3.7/site-packages/modin/core/execution/ray/common/task_wrapper.py\", line 40, in deploy_ray_func\n",
      "  File \"/tmp/ray/session_2022-07-06_02-59-12_340846_29218/runtime_resources/pip/11ec394aa27dc2f92256e9847ec87567ef3cace5/virtualenv/lib/python3.7/site-packages/modin/core/storage_formats/pandas/parsers.py\", line 622, in parse\n",
      "    df = pandas.read_parquet(fname, **kwargs)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 500, in read_parquet\n",
      "    **kwargs,\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 240, in read\n",
      "    path_or_handle, columns=columns, **kwargs\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1942, in read_table\n",
      "    use_pandas_metadata=use_pandas_metadata)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1778, in read\n",
      "    use_threads=use_threads\n",
      "  File \"pyarrow/_dataset.pyx\", line 491, in pyarrow._dataset.Dataset.to_table\n",
      "  File \"pyarrow/_dataset.pyx\", line 3235, in pyarrow._dataset.Scanner.to_table\n",
      "  File \"pyarrow/error.pxi\", line 143, in pyarrow.lib.pyarrow_internal_check_status\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/spec.py\", line 1578, in read\n",
      "    out = self.cache._fetch(self.loc, self.loc + length)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/caching.py\", line 399, in _fetch\n",
      "    out = self.cache[offset : offset + end - start]\n",
      "MemoryError\n",
      "Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::deploy_ray_func()\u001b[39m (pid=24638, ip=172.31.27.60)\n",
      "  File \"/home/emr-notebook/.local/lib/python3.7/site-packages/modin/core/execution/ray/common/task_wrapper.py\", line 40, in deploy_ray_func\n",
      "  File \"/tmp/ray/session_2022-07-06_02-59-12_340846_29218/runtime_resources/pip/11ec394aa27dc2f92256e9847ec87567ef3cace5/virtualenv/lib/python3.7/site-packages/modin/core/storage_formats/pandas/parsers.py\", line 622, in parse\n",
      "    df = pandas.read_parquet(fname, **kwargs)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 500, in read_parquet\n",
      "    **kwargs,\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 240, in read\n",
      "    path_or_handle, columns=columns, **kwargs\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1942, in read_table\n",
      "    use_pandas_metadata=use_pandas_metadata)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1778, in read\n",
      "    use_threads=use_threads\n",
      "  File \"pyarrow/_dataset.pyx\", line 491, in pyarrow._dataset.Dataset.to_table\n",
      "  File \"pyarrow/_dataset.pyx\", line 3235, in pyarrow._dataset.Scanner.to_table\n",
      "  File \"pyarrow/error.pxi\", line 143, in pyarrow.lib.pyarrow_internal_check_status\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/spec.py\", line 1578, in read\n",
      "    out = self.cache._fetch(self.loc, self.loc + length)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/caching.py\", line 399, in _fetch\n",
      "    out = self.cache[offset : offset + end - start]\n",
      "MemoryError\n",
      "Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::deploy_ray_func()\u001b[39m (pid=24638, ip=172.31.27.60)\n",
      "  File \"/home/emr-notebook/.local/lib/python3.7/site-packages/modin/core/execution/ray/common/task_wrapper.py\", line 40, in deploy_ray_func\n",
      "  File \"/tmp/ray/session_2022-07-06_02-59-12_340846_29218/runtime_resources/pip/11ec394aa27dc2f92256e9847ec87567ef3cace5/virtualenv/lib/python3.7/site-packages/modin/core/storage_formats/pandas/parsers.py\", line 622, in parse\n",
      "    df = pandas.read_parquet(fname, **kwargs)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 500, in read_parquet\n",
      "    **kwargs,\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 240, in read\n",
      "    path_or_handle, columns=columns, **kwargs\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1942, in read_table\n",
      "    use_pandas_metadata=use_pandas_metadata)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1778, in read\n",
      "    use_threads=use_threads\n",
      "  File \"pyarrow/_dataset.pyx\", line 491, in pyarrow._dataset.Dataset.to_table\n",
      "  File \"pyarrow/_dataset.pyx\", line 3235, in pyarrow._dataset.Scanner.to_table\n",
      "  File \"pyarrow/error.pxi\", line 143, in pyarrow.lib.pyarrow_internal_check_status\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/spec.py\", line 1578, in read\n",
      "    out = self.cache._fetch(self.loc, self.loc + length)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/caching.py\", line 399, in _fetch\n",
      "    out = self.cache[offset : offset + end - start]\n",
      "MemoryError\n",
      "Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::deploy_ray_func()\u001b[39m (pid=24638, ip=172.31.27.60)\n",
      "  File \"/home/emr-notebook/.local/lib/python3.7/site-packages/modin/core/execution/ray/common/task_wrapper.py\", line 40, in deploy_ray_func\n",
      "  File \"/tmp/ray/session_2022-07-06_02-59-12_340846_29218/runtime_resources/pip/11ec394aa27dc2f92256e9847ec87567ef3cace5/virtualenv/lib/python3.7/site-packages/modin/core/storage_formats/pandas/parsers.py\", line 622, in parse\n",
      "    df = pandas.read_parquet(fname, **kwargs)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 500, in read_parquet\n",
      "    **kwargs,\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 240, in read\n",
      "    path_or_handle, columns=columns, **kwargs\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1942, in read_table\n",
      "    use_pandas_metadata=use_pandas_metadata)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1778, in read\n",
      "    use_threads=use_threads\n",
      "  File \"pyarrow/_dataset.pyx\", line 491, in pyarrow._dataset.Dataset.to_table\n",
      "  File \"pyarrow/_dataset.pyx\", line 3235, in pyarrow._dataset.Scanner.to_table\n",
      "  File \"pyarrow/error.pxi\", line 143, in pyarrow.lib.pyarrow_internal_check_status\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/spec.py\", line 1578, in read\n",
      "    out = self.cache._fetch(self.loc, self.loc + length)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/caching.py\", line 399, in _fetch\n",
      "    out = self.cache[offset : offset + end - start]\n",
      "MemoryError\n",
      "Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::deploy_ray_func()\u001b[39m (pid=24638, ip=172.31.27.60)\n",
      "  File \"/home/emr-notebook/.local/lib/python3.7/site-packages/modin/core/execution/ray/common/task_wrapper.py\", line 40, in deploy_ray_func\n",
      "  File \"/tmp/ray/session_2022-07-06_02-59-12_340846_29218/runtime_resources/pip/11ec394aa27dc2f92256e9847ec87567ef3cace5/virtualenv/lib/python3.7/site-packages/modin/core/storage_formats/pandas/parsers.py\", line 622, in parse\n",
      "    df = pandas.read_parquet(fname, **kwargs)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 500, in read_parquet\n",
      "    **kwargs,\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 240, in read\n",
      "    path_or_handle, columns=columns, **kwargs\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1942, in read_table\n",
      "    use_pandas_metadata=use_pandas_metadata)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1778, in read\n",
      "    use_threads=use_threads\n",
      "  File \"pyarrow/_dataset.pyx\", line 491, in pyarrow._dataset.Dataset.to_table\n",
      "  File \"pyarrow/_dataset.pyx\", line 3235, in pyarrow._dataset.Scanner.to_table\n",
      "  File \"pyarrow/error.pxi\", line 143, in pyarrow.lib.pyarrow_internal_check_status\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/spec.py\", line 1578, in read\n",
      "    out = self.cache._fetch(self.loc, self.loc + length)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/caching.py\", line 399, in _fetch\n",
      "    out = self.cache[offset : offset + end - start]\n",
      "MemoryError\n",
      "Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::deploy_ray_func()\u001b[39m (pid=24638, ip=172.31.27.60)\n",
      "  File \"/home/emr-notebook/.local/lib/python3.7/site-packages/modin/core/execution/ray/common/task_wrapper.py\", line 40, in deploy_ray_func\n",
      "  File \"/tmp/ray/session_2022-07-06_02-59-12_340846_29218/runtime_resources/pip/11ec394aa27dc2f92256e9847ec87567ef3cace5/virtualenv/lib/python3.7/site-packages/modin/core/storage_formats/pandas/parsers.py\", line 622, in parse\n",
      "    df = pandas.read_parquet(fname, **kwargs)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 500, in read_parquet\n",
      "    **kwargs,\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 240, in read\n",
      "    path_or_handle, columns=columns, **kwargs\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1942, in read_table\n",
      "    use_pandas_metadata=use_pandas_metadata)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1778, in read\n",
      "    use_threads=use_threads\n",
      "  File \"pyarrow/_dataset.pyx\", line 491, in pyarrow._dataset.Dataset.to_table\n",
      "  File \"pyarrow/_dataset.pyx\", line 3235, in pyarrow._dataset.Scanner.to_table\n",
      "  File \"pyarrow/error.pxi\", line 143, in pyarrow.lib.pyarrow_internal_check_status\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/spec.py\", line 1578, in read\n",
      "    out = self.cache._fetch(self.loc, self.loc + length)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/caching.py\", line 399, in _fetch\n",
      "    out = self.cache[offset : offset + end - start]\n",
      "MemoryError\n",
      "Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::deploy_ray_func()\u001b[39m (pid=24638, ip=172.31.27.60)\n",
      "  File \"/home/emr-notebook/.local/lib/python3.7/site-packages/modin/core/execution/ray/common/task_wrapper.py\", line 40, in deploy_ray_func\n",
      "  File \"/tmp/ray/session_2022-07-06_02-59-12_340846_29218/runtime_resources/pip/11ec394aa27dc2f92256e9847ec87567ef3cace5/virtualenv/lib/python3.7/site-packages/modin/core/storage_formats/pandas/parsers.py\", line 622, in parse\n",
      "    df = pandas.read_parquet(fname, **kwargs)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 500, in read_parquet\n",
      "    **kwargs,\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 240, in read\n",
      "    path_or_handle, columns=columns, **kwargs\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1942, in read_table\n",
      "    use_pandas_metadata=use_pandas_metadata)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1778, in read\n",
      "    use_threads=use_threads\n",
      "  File \"pyarrow/_dataset.pyx\", line 491, in pyarrow._dataset.Dataset.to_table\n",
      "  File \"pyarrow/_dataset.pyx\", line 3235, in pyarrow._dataset.Scanner.to_table\n",
      "  File \"pyarrow/error.pxi\", line 143, in pyarrow.lib.pyarrow_internal_check_status\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/spec.py\", line 1578, in read\n",
      "    out = self.cache._fetch(self.loc, self.loc + length)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/caching.py\", line 399, in _fetch\n",
      "    out = self.cache[offset : offset + end - start]\n",
      "MemoryError\n",
      "Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::deploy_ray_func()\u001b[39m (pid=24638, ip=172.31.27.60)\n",
      "  File \"/home/emr-notebook/.local/lib/python3.7/site-packages/modin/core/execution/ray/common/task_wrapper.py\", line 40, in deploy_ray_func\n",
      "  File \"/tmp/ray/session_2022-07-06_02-59-12_340846_29218/runtime_resources/pip/11ec394aa27dc2f92256e9847ec87567ef3cace5/virtualenv/lib/python3.7/site-packages/modin/core/storage_formats/pandas/parsers.py\", line 622, in parse\n",
      "    df = pandas.read_parquet(fname, **kwargs)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 500, in read_parquet\n",
      "    **kwargs,\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 240, in read\n",
      "    path_or_handle, columns=columns, **kwargs\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1942, in read_table\n",
      "    use_pandas_metadata=use_pandas_metadata)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1778, in read\n",
      "    use_threads=use_threads\n",
      "  File \"pyarrow/_dataset.pyx\", line 491, in pyarrow._dataset.Dataset.to_table\n",
      "  File \"pyarrow/_dataset.pyx\", line 3235, in pyarrow._dataset.Scanner.to_table\n",
      "  File \"pyarrow/error.pxi\", line 143, in pyarrow.lib.pyarrow_internal_check_status\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/spec.py\", line 1578, in read\n",
      "    out = self.cache._fetch(self.loc, self.loc + length)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/caching.py\", line 399, in _fetch\n",
      "    out = self.cache[offset : offset + end - start]\n",
      "MemoryError\n",
      "Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::deploy_ray_func()\u001b[39m (pid=24638, ip=172.31.27.60)\n",
      "  File \"/home/emr-notebook/.local/lib/python3.7/site-packages/modin/core/execution/ray/common/task_wrapper.py\", line 40, in deploy_ray_func\n",
      "  File \"/tmp/ray/session_2022-07-06_02-59-12_340846_29218/runtime_resources/pip/11ec394aa27dc2f92256e9847ec87567ef3cace5/virtualenv/lib/python3.7/site-packages/modin/core/storage_formats/pandas/parsers.py\", line 622, in parse\n",
      "    df = pandas.read_parquet(fname, **kwargs)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 500, in read_parquet\n",
      "    **kwargs,\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 240, in read\n",
      "    path_or_handle, columns=columns, **kwargs\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1942, in read_table\n",
      "    use_pandas_metadata=use_pandas_metadata)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1778, in read\n",
      "    use_threads=use_threads\n",
      "  File \"pyarrow/_dataset.pyx\", line 491, in pyarrow._dataset.Dataset.to_table\n",
      "  File \"pyarrow/_dataset.pyx\", line 3235, in pyarrow._dataset.Scanner.to_table\n",
      "  File \"pyarrow/error.pxi\", line 143, in pyarrow.lib.pyarrow_internal_check_status\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/spec.py\", line 1578, in read\n",
      "    out = self.cache._fetch(self.loc, self.loc + length)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/caching.py\", line 399, in _fetch\n",
      "    out = self.cache[offset : offset + end - start]\n",
      "MemoryError\n",
      "Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::deploy_ray_func()\u001b[39m (pid=24638, ip=172.31.27.60)\n",
      "  File \"/home/emr-notebook/.local/lib/python3.7/site-packages/modin/core/execution/ray/common/task_wrapper.py\", line 40, in deploy_ray_func\n",
      "  File \"/tmp/ray/session_2022-07-06_02-59-12_340846_29218/runtime_resources/pip/11ec394aa27dc2f92256e9847ec87567ef3cace5/virtualenv/lib/python3.7/site-packages/modin/core/storage_formats/pandas/parsers.py\", line 622, in parse\n",
      "    df = pandas.read_parquet(fname, **kwargs)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 500, in read_parquet\n",
      "    **kwargs,\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pandas/io/parquet.py\", line 240, in read\n",
      "    path_or_handle, columns=columns, **kwargs\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1942, in read_table\n",
      "    use_pandas_metadata=use_pandas_metadata)\n",
      "  File \"/usr/local/lib64/python3.7/site-packages/pyarrow/parquet.py\", line 1778, in read\n",
      "    use_threads=use_threads\n",
      "  File \"pyarrow/_dataset.pyx\", line 491, in pyarrow._dataset.Dataset.to_table\n",
      "  File \"pyarrow/_dataset.pyx\", line 3235, in pyarrow._dataset.Scanner.to_table\n",
      "  File \"pyarrow/error.pxi\", line 143, in pyarrow.lib.pyarrow_internal_check_status\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/spec.py\", line 1578, in read\n",
      "    out = self.cache._fetch(self.loc, self.loc + length)\n",
      "  File \"/usr/local/lib/python3.7/site-packages/fsspec/caching.py\", line 399, in _fetch\n",
      "    out = self.cache[offset : offset + end - start]\n",
      "MemoryError\n"
     ]
    }
   ],
   "source": [
    "%%time\n",
    "\n",
    "import modin.pandas as pd\n",
    "\n",
    "df = pd.read_parquet(\"s3://dsoaws/parquet\")\n",
    "\n",
    "print(df.groupby(\"product_category\").count())"
   ]
  },
  {
   "cell_type": "raw",
   "id": "3010d71e-6ff4-4456-a1aa-27bd9acbadfe",
   "metadata": {},
   "source": []
  },
  {
   "cell_type": "raw",
   "id": "d4ef8645-430d-4620-89a4-77dfa1c5dc56",
   "metadata": {},
   "source": []
  },
  {
   "cell_type": "raw",
   "id": "390ade7c-10b7-4c13-89d5-161735a5abee",
   "metadata": {},
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
